(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var E4=function(a){a.ma("cardstatechange",a.Mi()&&a.Hm()?1:0)},F4=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Y1a=function(a){var b=g.Ml(a);
a=g.Pl(a);return new g.Bl(b.x,b.y,a.width,a.height)},Z1a=function(a){return Math.pow(a,3)},$1a=function(a){return 3*a*a-2*a*a*a},I4=function(a){a=g.Pa(a);
delete G4[a];g.Bf(G4)&&H4&&H4.stop()},b2a=function(){H4||(H4=new g.bo(function(){a2a()},20));
var a=H4;a.isActive()||a.start()},a2a=function(){var a=g.Sa();
g.nf(G4,function(b){c2a(b,a)});
g.Bf(G4)||b2a()},J4=function(a,b,c,d){g.vo.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.F=null},c2a=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.F);a.F=b;d2a(a,a.progress);1==a.progress?(a.j=0,I4(a),a.onFinish(),a.xA()):a.Rc()&&a.XF()},d2a=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},e2a=function(a,b){g.bf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},K4=function(a,b,c,d,e){J4.call(this,b,c,d,e);
this.element=a},f2a=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
K4.call(this,a,b,c,d,e)},L4=function(a){g.M.call(this);
this.u=a||window;this.j=[]},M4=function(a){return a.baseUrl||null},N4=function(a,b){return g.Bm(g.Uk(a,b),function(c){return!!c})},g2a=function(a,b,c){function d(V){var aa=V.hovercardButton;
if(!aa)return null;aa=aa.subscribeButtonRenderer;if(!aa)return null;var P=f(aa.unsubscribedButtonText),pa=f(aa.subscribedButtonText);if(aa.subscribed){var Aa=f(aa.subscriberCountWithUnsubscribeText);var ta=f(aa.subscriberCountText)}else Aa=f(aa.subscriberCountText),ta=f(aa.subscriberCountWithSubscribeText);var wa=null;if(V.signinEndpoint){wa=F4(V,"signinEndpoint","webNavigationEndpointData","url");if(!wa){var Ba,ya,Ca;wa=null==(Ba=aa.signInEndpoint)?void 0:null==(ya=Ba.commandMetadata)?void 0:null==
(Ca=ya.webCommandMetadata)?void 0:Ca.url}if(!wa)return null}return P&&(pa||wa)?{subscribed:aa.subscribed,subscribeText:P,subscribeCount:Aa,unsubscribeText:pa,unsubscribeCount:ta,enabled:aa.enabled,signinUrl:wa,classic:V.useClassicSubscribeButton}:null}
function e(V){if(V){var aa=[],P=V.videoId;P&&aa.push("v="+P);(P=V.playlistId)&&aa.push("list="+P);(V=V.startTimeSeconds)&&aa.push("t="+V);return"/watch?"+aa.join("&")}}
function f(V){if(!V)return null;var aa=V.simpleText;return aa?aa:V.runs?g.Uk(V.runs,function(P){return P.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,w=null,y=null,z=!1,B=null,E=null,G=null,C=null,I=null,K=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:(K=l.watchEndpoint,m=e(K)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:(K=l.watchEndpoint,m=e(K)),n=!1,q=a,w=f(b.playlistLength);
else if("CHANNEL"===h){if(z=F4(l,"browseEndpoint","browseId"))y=z,m="/channel/"+y;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((G=F4(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(C=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=F4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=F4(b,"title","accessibility","accessibilityData","label");var L=b.endpoint?b.endpoint.clickTrackingParams:
null,R="";if(b.metadata){var Q=f(b.metadata);Q&&(R=Q)}return{id:"element-"+c,type:h,title:f(b.title),metadata:R,callToAction:f(b.callToAction),wP:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,isLiveVideo:p,playlistLength:w,channelId:y,subscribeButton:B,subscribersText:E,isSubscribe:z,targetUrl:m||null,k0:n,sessionData:L?{itct:L}:null,z6:q,Iy:a?a:
null,isPlaceholder:b.isPlaceholder,impressionUrls:N4(b.impressionUrls||[],M4),R_:N4(b.hovercardShowUrls||[],M4),clickUrls:N4(l.loggingUrls||[],M4),visualElement:g.pz(b.trackingParams),productPrice:C,additionalFeesText:I,watchEndpoint:K||null}},h2a=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:N4(a.impressionUrls||[],M4),elements:N4(a.elements||[],function(d,e){return g2a(b,d,e)})};
a.trackingParams&&(c.visualElement=g.pz(a.trackingParams));return c},i2a=function(a){g.mO.call(this,a);
this.B=this.endscreen=null;this.j={};this.F={};this.C=this.u=null;this.J=[];this.Z=!0;this.I=0;a=a.V();this.S=g.SF(a)||g.WF(a);this.ea=a.experiments.kb("web_rounded_thumbnails");this.events=new g.VD(this);g.N(this,this.events);this.events.T(this.player,g.mA("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.nA("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Bb);this.events.T(window,"focus",this.F4);this.load();var b=g.lh("STYLE");(g.ah("HEAD")[0]||
document.body).appendChild(b);g.af(this,function(){g.ph(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},j2a=function(a){return a.player.getVideoData().F?"current":a.S?"new":"current"},O4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},k2a=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=h2a(f,j2a(a))));P4(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Pu;d&&(c.postParams={ad_tracking:d});if(b=g.YBa(b))if(b=g.pg(b),b=g.ng(b))a.B=g.Ju(b,c)},P4=function(a,b,c){c=void 0===c?!0:c;
a.player.zf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.F={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&l2a(a);c=[];d=new g.kA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.X({D:"div",K:"ytp-ce-shadow"}),g.IN(a.player,a.u.element,4),a.C=new g.PL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=m2a(a,e);if(f){a.j[e.id]=f;a.F[e.id]=e;g.IN(a.player,f.element,4);var h=new g.kA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);n2a(a,
f,e)}else g.mz(new g.Zv("buildEndscreenElement null",e))}a.player.le(c);a.Bb()}},l2a=function(a){var b=g.vz(),c=g.wz();
c&&b&&a.endscreen.visualElement&&g.Az(void 0,c,b,[a.endscreen.visualElement])},m2a=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={D:"div",Ga:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.Iy||"","aria-hidden":"true"},W:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",X:Q4(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",X:{href:R4(a,b.targetUrl),tabindex:"-1"},W:[{D:"div",Ga:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.zo(b.title||"")},qa:b.title},{D:"div",K:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
qa:b.videoDuration||void 0}]}]};c=new g.X(a);break;case "PLAYLIST":a={D:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.Iy||"","aria-hidden":"true"},W:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",X:Q4(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",X:{href:R4(a,b.targetUrl),tabindex:"-1"},W:[{D:"div",Ga:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.zo(b.title||"")},qa:b.title},{D:"div",K:"ytp-ce-playlist-count",
W:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.X(a);break;case "CHANNEL":c={D:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.Iy||"","aria-hidden":"true"},W:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",W:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",
W:[{D:"div",K:"ytp-ce-expanding-overlay-body",W:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{D:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],X:{href:R4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.zo(b.title||"")},qa:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",W:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{D:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],qa:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",X:Q4(b)}]};c=new g.X(c);var d=g.bh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.ko(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.qP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ga:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.Iy||"","aria-hidden":"true"},W:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",W:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",
W:[{D:"div",K:"ytp-ce-expanding-overlay-body",W:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{D:"div",K:"ytp-ce-website-title",X:{dir:g.zo(b.title||"")},qa:b.title},{D:"div",K:"ytp-ce-website-metadata",qa:b.metadata},{D:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],X:{href:R4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",X:Q4(b)},{D:"div",K:"ytp-ce-expanding-icon",X:o2a(b.iconUrl)}]};c=new g.X(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",W:[{D:"div",K:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({D:"div",K:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={D:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.Iy||"","aria-hidden":"true"},W:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",W:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},
{D:"div",K:"ytp-ce-expanding-overlay-content",W:[{D:"div",K:"ytp-ce-expanding-overlay-body",W:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{D:"div",K:"ytp-ce-merchandise-title",X:{dir:g.zo(b.title||"")},qa:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",qa:b.metadata},{D:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:R4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",X:Q4(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",
W:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",qa:b.callToAction||void 0}]}]},c=new g.X(a)}b.isPlaceholder&&g.ko(c.element,"ytp-ce-placeholder");return c},Q4=function(a){if(a.wP)var b=a.wP.thumbnails;
return o2a(b?b[b.length-1].url:null)},o2a=function(a){return a?{style:"background-image: url("+a+")"}:{}},n2a=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.Z&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.ko(b.element,"ytp-ce-force-expand"),S4(a,c.id,!0)):(g.mo(b.element,"ytp-ce-force-expand"),g.mo(b.element,"ytp-ce-element-hover"),S4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){p2a(a,b,c)});
b.Ra("mouseleave",function(){q2a(a,b,c)});
a.player.V().isMobile||b.Ra("click",function(){g.ko(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){r2a(a,c,m)});
b.Ra("keypress",function(m){r2a(a,c,m)});
b.Ra("focus",function(){p2a(a,b,c)});
b.Ra("blur",function(){q2a(a,b,c)});
b.Ra("touchstart",function(){p2a(a,b,c)});
var l=g.dh("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.mo(b.element,"ytp-ce-element-hover");g.mo(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.Z=9===m.keyCode&&!m.shiftKey});
d(g.dh("ytp-sb-subscribe",b.element));d(g.dh("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},r2a=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.jo(d,"ytp-ce-element");){g.jo(d,"subscribe-label")&&s2a(a,b);
if(g.jo(d,"ytp-ce-channel-subscribe"))return;d=g.qh(d)}if(!d||g.jo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])q2a(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.z6)s2a(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.pg(R4(a,b.targetUrl)),g.pM(g.ng(c),void 0,b.sessionData);else{var e=g.mG(a.player.V())||a.player.getVideoData().F,f=function(){var h=R4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.vu(h);e&&n&&(n.v||
n.list)?a.player.Yl(n.v,l,n.list,!1,void 0,m||void 0):g.oM(h,l)};
s2a(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},R4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.wG(a)+b}else return"";return b},p2a=function(a,b,c){g.jo(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.ko(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.bo(function(){g.ko(b.element,"ytp-ce-element-hover")},200)).start():g.ko(b.element,"ytp-ce-element-hover"),T4(a,c.R_),S4(a,c.id,!0))},q2a=function(a,b,c){g.mo(b.element,"ytp-ce-element-hover");
g.mo(b.element,"ytp-ce-force-expand");S4(a,c.id,!1)},S4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.j[e].element,"ytp-ce-element-shadow-show",c)},T4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||O4(a))c&&c();else{b=t2a(a,b);var e=0,f=!1,h=new g.bo(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Zw(b[a],d)}},s2a=function(a,b,c){T4(a,b.clickUrls,c);
(a=g.wz())&&b.k0&&g.rK(a,b.visualElement)},t2a=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(u2a(b[d],c));return a},u2a=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},v2a=function(a){return"string"===typeof a?a:""},U4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},w2a=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},V4=function(a){return a.value?a.value:null},W4=function(a){if(!a)return null;
var b=g.pg(v2a(a.value));b=g.ng(b);if(!b)return null;var c=U4(a.target,x2a,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new w2a(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},y2a=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},B2a=function(a){if(!a)return null;
var b=U4(a.type,z2a),c=U4(a.trigger,A2a);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=W4(a?a:null);return b?new y2a(b,c,a):null},C2a=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},D2a=function(a,b){return g.Tb(a.action,b)},E2a=function(a,b){this.context=a;
this.j=b},F2a=function(a){return a.customMessage?X4("div","iv-card-message",a.customMessage):""},Y4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",X:{style:a},W:c}},G2a=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(X4("li","",c.value));return{D:"ul",K:"iv-card-meta-info",W:b}},X4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.zo(c);return{D:a,X:b,qa:c}},H2a=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Sy&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Sy+");");c.dir=g.zo(a.customMessage);var d=[{D:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Ga:b,X:c,W:d}},Z4=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},I2a=function(a,b){this.merchant=a;
this.price=b},J2a=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},K2a=function(a,b){return b?b:J2a(a)?"current":"new"},$4=function(a,b){g.M.call(this);
var c=this;this.element=a;this.context=b;this.tb=!1;this.Ya=new Map;this.eb=new Map;this.context.G.addEventListener(g.mA("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.nA("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)})},a5=function(a,b,c,d,e,f,h){a.context.j.Ra(b,"click",function(l){a.YF(c,d,e,f||[],h||0,l)});
a.context.j.Ra(b,"touchstart",function(){a.tb=!1});
a.context.j.Ra(b,"touchmove",function(){a.tb=!0})},L2a=function(a){var b;
return(null==(b=g.hv(a,g.QH))?0:b.url)?g.hv(a,g.QH).url:(a=g.hv(a,g.UG))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},b5=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
KT:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
mF:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},M2a=function(a,b,c){$4.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Qa=this.Wb=this.B=this.isInitialized=!1;this.ya=null;this.cards=[];this.Ab=this.S=this.La=this.F=this.Ta=this.j=null;this.ea=[];this.oa=this.J=this.vf=this.Ia=null;this.I=0;this.Ba=new g.bo(function(){},c.Y.Of?4E3:3E3);
g.N(this,this.Ba);this.ob=new g.bo(function(){});
g.N(this,this.ob);this.xa=new E2a(c,function(e,f,h,l,m,n){a5(d,e,f,h,l,m,n)});
this.Z=new g.X({D:"div",K:"iv-drawer",X:{id:"iv-drawer"},W:[{D:"div",K:"iv-drawer-header",X:{"aria-role":"heading"},W:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Ga:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"\u96b1\u85cf\u8cc7\u8a0a\u5361",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.N(this,this.Z);this.C=this.Z.element;this.jb=new g.PL(this.Z,330);g.N(this,this.jb);this.Nb=g.dh("iv-drawer-header-text",this.C);this.u=g.dh("iv-drawer-content",this.C);this.addCueRange(0,
1E3*c.videoData.lengthSeconds,"",function(){d.Wb&&c5(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Wb=d.B)&&d5(d)});
this.G.addEventListener("videodatachange",this.oq.bind(this))},N2a=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){c5(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){d5(a)});
var c=b.headerText;g.sh(a.Nb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ia=g.pz(b.trackingParams);a.J=g.pz(b.closeTrackingParams);a.vf=g.pz(b.iconTrackingParams)},O2a=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.V().experiments.kb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.rA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},Jm:null,Wj:e.trackingParams?g.pz(e.trackingParams):null,vf:f&&f.trackingParams?g.pz(f.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,Sy:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};e5(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.rA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,f),sponsored:!1,tracking:b5(f,e,f.command),Jm:f.trackingParams?g.pz(f.trackingParams):null,Wj:e.trackingParams?g.pz(e.trackingParams):null,vf:l&&l.trackingParams?g.pz(l.trackingParams):null,imageUrl:g5(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.rA(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,Sy:null,title:f.title?g.rA(f.title):"",customMessage:f.callToAction?g.rA(f.callToAction):"",url:g.hv(f.command,g.QH).url?W4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.hv(f.command,g.QH).url}):null,onClickCommand:null};e5(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.rA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,e),sponsored:!1,tracking:b5(e,f,e.endpoint),Jm:e.trackingParams?g.pz(e.trackingParams):null,Wj:f.trackingParams?g.pz(f.trackingParams):null,vf:l&&l.trackingParams?g.pz(l.trackingParams):null,channelId:g.hv(e.endpoint,h5).browseId,customMessage:e.customText?g.rA(e.customText):null,profileImageUrl:g5(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.rA(e.channelName):"",metaInfo:[e.subscriberCountText?g.rA(e.subscriberCountText):""],url:W4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.hv(e.endpoint,h5).canonicalBaseUrl?g.hv(e.endpoint,h5).canonicalBaseUrl:"/channel/"+g.hv(e.endpoint,h5).browseId}),onClickCommand:null};e5(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.rA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,e),sponsored:!1,tracking:b5(e,f,e.action),Jm:e.trackingParams?g.pz(e.trackingParams):null,Wj:f.trackingParams?g.pz(f.trackingParams):null,vf:l&&l.trackingParams?g.pz(l.trackingParams):null,oB:g5(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.rA(e.customMessage):null,playlistVideoCount:g.rA(e.playlistVideoCount),title:e.playlistTitle?g.rA(e.playlistTitle):"",metaInfo:[e.channelName?
g.rA(e.channelName):"",e.videoCountText?g.rA(e.videoCountText):""],url:W4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:L2a(e.action)}),onClickCommand:null};e5(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.rA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,e),sponsored:!1,tracking:b5(e,f,e.action),Jm:e.trackingParams?g.pz(e.trackingParams):null,Wj:f.trackingParams?g.pz(f.trackingParams):null,vf:l&&l.trackingParams?g.pz(l.trackingParams):null,oB:g5(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.rA(e.lengthString):null,customMessage:e.customMessage?g.rA(e.customMessage):null,title:e.videoTitle?g.rA(e.videoTitle):"",metaInfo:[e.channelName?
g.rA(e.channelName):"",e.viewCountText?g.rA(e.viewCountText):""],isLiveNow:!!e.badge,url:W4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:L2a(e.action)}),onClickCommand:null};e5(a,b)}}}}}a.I++},g5=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},f5=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Q2a=function(a,b){if(b=P2a(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.ph(b.vH),g.$b(a.cards,b),a.rC(),i5(a)},c5=function(a,b,c){if(!a.B){a.jb.show();
a.Ta=new g.bo(function(){g.ko(a.context.G.getRootNode(),g.GT.IV_DRAWER_OPEN)},0);
a.Ta.start();a.ya=g.rx(a.u,"mousewheel",function(h){a.Ba.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.wz();d&&a.Ia&&a.J&&g.pK(d,[a.Ia,a.J]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.gR||(f.gR=!0,R2a(a.context.logger,f.card.tracking.impression,b)),d&&g.pK(d,[f.card.Jm]);E4(a.G);c&&(a.F=new g.bo(function(){a.La=a.S;a.Ab.focus()},330),a.F.start())}},d5=function(a){a.B&&(a.jb.hide(),g.sx(a.ya),a.ya=null,g.mo(a.context.G.getRootNode(),g.GT.IV_DRAWER_OPEN),a.B=!1,E4(a.G),a.F&&a.F.stop(),a.F=new g.bo(function(){a.La&&(a.La.focus(),a.La=null)},330),
a.F.start())},T2a=function(a){g.lo(a.element,[g.GT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.IN(a.G,a.C,5);S2a(a);a.S=g.dh("ytp-cards-button",a.G.getRootNode());a.Ab=g.dh("iv-drawer-close-button",a.C);a.isInitialized=!0},S2a=function(a){var b=g.dh("iv-drawer-close-button",a.C);
a.context.j.Ra(b,"click",a.iZ,a);a.context.j.Ra(a.u,"touchend",function(){a.Ba.start()});
a.context.j.Ra(a.u,"scroll",a.BZ,a);a.context.u.subscribe("onHideControls",function(){a.Qa=!0});
a.context.u.subscribe("onShowControls",function(){a.Qa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Qa=g.jo(a.G.getRootNode(),"ytp-autohide")});
a.ea.push(g.Lx("iv-button-shown",a.x0,a));a.ea.push(g.Lx("iv-button-hidden",a.w0,a));a.ea.push(g.Lx("iv-teaser-shown",a.oV,a));a.ea.push(g.Lx("iv-teaser-hidden",a.y0,a));a.ea.push(g.Lx("iv-teaser-clicked",a.nV,a))},U2a=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.hv(b.onClickCommand,g.TZa))?void 0:c.targetId)?(a.oa=b,!0):!1},V2a=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,h=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.hv(h[0],g.q0a))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}}a.oa=b;return!1},e5=function(a,b){if(!U2a(a,b)||V2a(a,b)){var c=W2a(a,b);
if(c){var d={card:b,vH:c.element,gR:!1};if(!b.onClickCommand){a.isInitialized||T2a(a);Q2a(a,b.id);var e=X2a(a,d);g.kc(a.cards,e,0,d);c.Ca(a.u,e);a.rC()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,i5(a),Y2a(a,d),c5(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&Z2a(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Z2a(a,d)}),i5(a))}}},W2a=function(a,b){switch(b.type){case "simple":var c=a.xa;
var d=b.displayDomain?{D:"div",K:"iv-card-image-text",qa:b.displayDomain}:void 0;var e=H2a(b);d={D:"div",Ga:["iv-card"],W:[{D:"a",K:"iv-click-target",X:{href:b.url?V4(b.url)||"":""},W:[Y4(b.imageUrl,d),{D:"div",K:"iv-card-content",W:[X4("h2",void 0,b.title),e]}]}]};d=new g.X(d);Z4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.xa;d={D:"div",Ga:["iv-card","iv-card-channel"],W:[{D:"a",Ga:["iv-click-target"],X:{href:V4(b.url)||"","data-ytid":b.channelId},W:[Y4(b.profileImageUrl),
{D:"div",K:"iv-card-content",W:[F2a(b),{D:"h2",K:"iv-card-primary-link",qa:b.title},G2a(b)]}]}]};d=new g.X(d);Z4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.xa;d={D:"div",Ga:["iv-card","iv-card-playlist"],W:[{D:"a",K:"iv-click-target",X:{href:V4(b.url)||""},W:[Y4(b.oB,{D:"div",K:"iv-card-image-overlay",W:[{D:"span",K:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",W:[F2a(b),X4("h2","iv-card-primary-link",b.title),G2a(b)]}]}]};
d=new g.X(d);Z4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.xa;var f=!g.Xb(b.offers);d=["iv-card"];e="";var h=H2a(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({D:"div",K:"iv-card-offer-price",qa:h.price}),h.merchant&&f.push({D:"div",K:"iv-card-offer-merchant",qa:h.merchant}),h={D:"div",W:f});f=b.url?V4(b.url)||"":"";d={D:"div",Ga:d,X:{tabindex:"0"},W:[{D:"a",Ga:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",W:[b.sponsored?{D:"div",K:"iv-card-sponsored",W:["\u8d0a\u52a9\u5546",{D:"div",K:"iv-ad-info-container",W:[{D:"div",K:"iv-ad-info",qa:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",W:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",X:{href:f},W:[X4("h2",e,b.title),h]}]}]};d=new g.X(d);e=g.lh("span");g.sh(e,"\u60a8\u4e4b\u6240\u4ee5\u770b\u5230\u9019\u9805\u7522\u54c1\uff0c\u662f\u56e0\u70ba\u6211\u5011\u8a8d\u70ba\u7522\u54c1\u8207\u5f71\u7247\u76f8\u95dc\u3002Google \u53ef\u80fd\u6703\u5411\u5546\u5bb6\u6536\u53d6\u5ee3\u544a\u8cbb\u7528\u3002");
d.Pd(e,"adInfo");Z4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.xa;d=b.videoDuration?{D:"span",K:"iv-card-video-duration",qa:b.videoDuration}:void 0;e=b.isLiveNow?{D:"span",Ga:["yt-badge","yt-badge-live"],qa:"\u76f4\u64ad\u4e2d"}:null;f={D:"div",Ga:["iv-card","iv-card-video"],W:[{D:"a",K:"iv-click-target",X:{href:(null==(h=b.url)?void 0:V4(h))||""},W:[Y4(b.oB,d),{D:"div",K:"iv-card-content",W:[F2a(b),X4("h2","iv-card-primary-link",b.title),G2a(b),e]}]}]};d=new g.X(f);Z4(c,
g.ch("iv-click-target",d.element),b,b.url);b=d;break;default:return null}a.G.V().experiments.kb("web_rounded_containers")&&g.ko(b.element,"ytp-rounded-info");return b},X2a=function(a,b){if(0===a.cards.length)return 0;
a=g.Vb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},$2a=function(a){return a.j?"productListing"===a.j.card.type:g.Yd(a.cards,function(b){return"productListing"===b.card.type})},i5=function(a){g.O(a.G.getRootNode(),"ytp-cards-shopping-active",$2a(a))},Z2a=function(a,b){if(!g.jo(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.wz(),d=a.j?a.j.card.vf:a.vf;
c&&d&&g.qK(c,[d]);a.j=b;i5(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.yx(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.ob.isActive()||((!a.B||!a.Ba.isActive()&&a.Qa)&&Y2a(a,b),a.ob.start(910+b.card.teaserDurationMs))}},Y2a=function(a,b){a.Z.rb?(b=new J4([0,
a.u.scrollTop],[0,b.vH.offsetTop],600,$1a),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.cL(a.Z,!0),a.u.scrollTop=b.vH.offsetTop,g.cL(a.Z,!1))},j5=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},P2a=function(a,b){return g.Tb(a.cards,function(c){return c.card.id===b})},k5=function(a,b,c){$4.call(this,a,b);
this.annotation=c;this.isActive=!1},a3a=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},l5=function(a,b,c){k5.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.F=null},b3a=function(a,b){var c=void 0===c?0:c;
var d=Y1a(b).width;g.Kl(b,d);c=new f2a(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Z1a);g.N(a,c);a.context.B.Ra(c,"begin",function(){g.Ql(b,!0)});
c.play()},e3a=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ga:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({D:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.qP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.Ca(d));var f=a.createElement({D:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Ql(h,!1);a.context.Y.N("web_rounded_containers")&&g.ko(h,"ytp-rounded-branding-context");var l=a.createElement({D:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.El(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.bo(function(){c3a(a,h,l)},500);
g.N(a,a.B);a.context.j.Ra(a.element,"mouseover",function(){d3a(a,h,l,f,b.image_height)});
a.context.j.Ra(a.element,"mouseout",function(){a.B.start()})}},d3a=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Pl(b);a.j||(b.style.width=g.Jl(f.width,!0),c.style.width=g.Jl(f.width,!0));g.El(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.El(d,"right","1px");a.C=!0;g.Ql(b,!0);a.F=new g.bo(function(){g.ko(this.element,"iv-branding-active")},0,a);
a.F.start()}},c3a=function(a,b,c){g.mo(a.element,"iv-branding-active");
a.I=new g.bo(function(){g.Ql(b,!1);a.j||(c.style.width=g.Jl(0,!0))},250);
a.I.start();a.C=!1},f3a=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},g3a=function(a,b,c){k5.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.Z=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({D:"div",Ga:["iv-promo-contents"]});this.F=new g.bo(function(){d.j.setAttribute("aria-hidden","true");g.Ql(d.B,!1);g.Ql(d.u,!0)},700,this);
g.N(this,this.F)},i3a=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","\u5ba3\u50b3");a.element.tabIndex=0;var e=a.annotation.Be(),f=b.image_url;if(f){var h=a.createElement({D:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&a5(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.Eg(f,V4(e)),a.j=f):a.j=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",W:[{D:"strong",
qa:b.text_line_1}]});var m=a.createElement({D:"p",W:[{D:"span",K:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ga:["iv-button","iv-promo-button"],W:[{D:"span",K:"iv-button-content",qa:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&a5(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.ko(a.j,
"iv-click-target");e&&a5(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",W:[{D:"span",qa:b.text_line_1}]}),m=a.createElement({D:"p",W:[{D:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ga:["yt-badge","iv-promo-badge-live"],qa:"\u76f4\u64ad\u4e2d"})),g.ko(a.j,"iv-click-target"),e&&a5(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);
p&&a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.u=a.createElement({D:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="\u5c55\u958b\n";a.context.j.Ra(a.u,"click",function(q){h3a(a,5E3,q)});
c.appendChild(a.u);g.Ql(a.u,!1);a.context.j.Ra(a.element,"mouseover",a.v_,a);a.context.j.Ra(a.element,"mouseout",a.u_,a);a.context.j.Ra(a.element,"touchend",function(q){h3a(a,5E3,q)});
a.B=a.createElement({D:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="\u95dc\u9589";a.context.j.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.q_:a.p_,a);c.appendChild(a.B);g.lo(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},h3a=function(a,b,c){c.stopPropagation();
j3a(a);k3a(a,b);a.j.focus()},l3a=function(a){a.isCollapsed||a.S||a.C||(g.ko(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.F.start())},j3a=function(a){a.F.stop();
a.isCollapsed&&(g.no(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Ql(a.u,!1),g.Ql(a.B,!0))},k3a=function(a,b){a.C||(a.C=g.Qh(function(){m3a(this);
l3a(this)},b,a))},m3a=function(a){a.C&&(g.D.clearTimeout(a.C),a.C=null)},n3a=function(a){this.G=a},R2a=function(a,b,c){b&&(c?m5(a,b.map(function(d){return g.Vn(d,c)})):m5(a,b))},m5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Zw(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},o3a=function(a){g.mO.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new n3a(this.player);this.F=new g.VD(this);this.C=this.Qn=null;this.events=new g.VD(this);this.J=this.j=null;this.S=[];g.N(this,this.F);this.F.T(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.F.T(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.F.T(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.F.T(this.player,"resize",function(d){b.ma("resize",d)});
this.F.T(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.pV,this);this.subscribe("resize",this.jE,this);this.player.V().oa.subscribe("vast_info_card_add",this.tS,this);g.N(this,this.events);this.Z=this.createElement({D:"div",K:"video-custom-annotations"});this.u=new g.X({D:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.N(this,this.u);g.IN(this.player,this.u.element,4);this.u.hide();this.B=new g.X({D:"div",Ga:["ytp-iv-video-content"]});g.N(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.ou()&&this.load();var c=this.createElement({D:"style"});(g.ah("HEAD")[0]||document.body).appendChild(c);g.af(this,function(){g.ph(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},p3a=function(a){a=a.createElement({D:"div",
Ga:["annotation","annotation-type-custom"]});g.Ql(a,!1);return a},q3a=function(a,b){b=!b.isCued()&&!g.W(b,1024);
g.cL(a.u,b);g.cL(a.B,b)},r3a=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(r3a(a,e))}return c},v3a=function(a){var b=a.player.getVideoData();
if(b.eb){var c=a.player.V().oa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Du(h)&&h.responseXML?h.responseXML:null)&&s3a(a,h)}};
g.Nv()&&(d.onFinish=t3a(a,d.onFinish));d.postParams={ic_only:"1"};u3a(d,c);g.Ju(b.eb,d)}}},u3a=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Ty&&(a.postParams.ic_coll=b.Ty);b.xC&&(a.postParams.ic_xml=b.xC);b.sB&&(a.postParams.ic_track=b.sB)},w3a=function(a){var b=new g.X({D:"div"});
g.Ql(b.element,!1);var c=new M2a(a.player,b.element,n5(a));g.N(c,b);b.Ca(a.u.element);c.bB();return c},n5=function(a){if(!a.J){var b=new L4(a);
g.N(a,b);var c=new g.Uj(a);g.N(a,c);a.J=new f3a(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Yg)}return a.J},s3a=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.wz();if(e){var f=g.vz();f&&g.Az(void 0,e,f,[g.pz(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=r3a(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=U4(f.type,x3a),p=U4(f.style,y3a),q=v2a(f.data),r=0!==q.length?JSON.parse(q):{};var w=f.action;f=B2a;if(null==w)var y=null;else if(g.Ma(w)){l=[];for(var z=g.t(w),B=z.next();!B.done;B=z.next()){var E=f(B.value);
E&&l.push(E)}y=l}else{var G=f(w);y=G?[G]:[]}e=m&&n?new C2a(m,n,p,y,r):null}else e=null}catch(Q){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var C=p3a(f),I=null;switch(l.type){case "branding":if(f.player.V().Yc)break;f.u.element.appendChild(C);I=new l5(C,n5(f),l);break;case "promotion":g.IN(f.player,C,4),I=new g3a(C,n5(f),l)}I&&I.bB();if(f=I)g.N(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=w3a(a),g.N(a,a.j));if("card"===e.type){c=a.j;var K=e&&e.data&&e.data.card_type;
f=e.data;if(K)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,KT:l.teaser_impression,mF:l.teaser_click},C=f.tracking_params||{},I=null,K){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Jm:C.card?g.pz(C.card):null,Wj:C.teaser?g.pz(C.teaser):null,vf:C.icon?g.pz(C.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};e5(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
Jm:C.card?g.pz(C.card):null,Wj:C.teaser?g.pz(C.teaser):null,vf:C.icon?g.pz(C.icon):null,oB:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};e5(c,e);break;case "productListing":f.signin_url&&(I=W4({target:"current",value:f.signin_url}));K=[];for(var L=f.offers||[],R=0;R<L.length;R++)K.push(new I2a(g.Vg(L[R].merchant),
g.Vg(L[R].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Jm:C.card?g.pz(C.card):null,Wj:C.teaser?g.pz(C.teaser):null,vf:C.icon?g.pz(C.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Sy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),B8a:I,A8a:f.signin_title?f.signin_title:void 0,z8a:f.signin_message?f.signin_message:void 0,offers:K,onClickCommand:null};e5(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Jm:C.card?g.pz(C.card):
null,Wj:C.teaser?g.pz(C.teaser):null,vf:C.icon?g.pz(C.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Sy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};e5(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Jm:C.card?g.pz(C.card):null,Wj:C.teaser?g.pz(C.teaser):null,vf:C.icon?g.pz(C.icon):null,oB:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},e5(c,e)}}else N2a(a.j,e);c=
!0}}c&&(E4(a.player),a.jE())},z3a=function(a,b){var c=!1;
a.j||(a.j=w3a(a),g.N(a,a.j));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(O2a(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.rA(b.headerText):"",g.sh(c.Nb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ia=b.trackingParams?g.pz(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.pz(b.closeButton.infoCardIconRenderer.trackingParams):null,c.vf=b.icon.infoCardIconRenderer.trackingParams?
g.pz(b.icon.infoCardIconRenderer.trackingParams):null,E4(a.player),a.jE())},A3a=function(a,b,c,d,e){if(!a.player.V().Yc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new y2a("openUrl","click",new w2a("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.rA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.rA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.rA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.rA(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.rA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.rA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new C2a(c,"branding","branding",f,d);l=p3a(a);a.u.element.appendChild(l);f=new l5(l,n5(a),f);f.bB();g.N(f,f);a.I[c]=f}},t3a=function(a,b){return function(){var c=
g.za.apply(0,arguments);
a.isDisposed()||a.S.push(g.Yn.Aj(function(){b.apply(null,g.u(c))}))}},B3a=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.BN.prototype.yx=g.ca(17,function(a,b){var c=g.EO(this.xb());c&&c.yx(a,b)});
var G4={},H4=null;g.Ta(J4,g.vo);g.k=J4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Rc())return!1;I4(this);this.startTime=a=g.Sa();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.F=this.startTime;this.progress||this.fE();this.Gk("play");-1==this.j&&this.Gk("resume");this.j=1;var b=g.Pa(this);b in G4||(G4[b]=this);b2a();c2a(this,a);return!0};
g.k.stop=function(a){I4(this);this.j=0;a&&(this.progress=1);d2a(this,this.progress);this.Gk("stop");this.xA()};
g.k.pause=function(){this.Rc()&&(I4(this),this.j=-1,this.Gk("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.Gk("destroy");J4.Ye.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.XF=function(){this.Gk("animate")};
g.k.Gk=function(a){this.dispatchEvent(new e2a(a,this))};
g.Ta(e2a,g.bf);g.Ta(K4,J4);K4.prototype.C=function(){};
K4.prototype.XF=function(){this.C();K4.Ye.XF.call(this)};
K4.prototype.xA=function(){this.C();K4.Ye.xA.call(this)};
K4.prototype.fE=function(){this.C();K4.Ye.fE.call(this)};
g.Ta(f2a,K4);f2a.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var h5=new g.$o("browseEndpoint");g.v(L4,g.M);L4.prototype.Ra=function(a,b,c,d){c=(0,g.Qa)(c,d||this.u);a=g.rx(a,b,c);this.j.push(a);return a};
L4.prototype.OD=function(a,b,c,d){c=(0,g.Qa)(c,d||this.u);a=g.Goa(a,b,c);this.j.push(a);return a};
L4.prototype.zc=function(a){g.sx(a);g.$b(this.j,a)};
L4.prototype.ra=function(){g.sx(this.j);this.j.length=0;g.M.prototype.ra.call(this)};g.v(i2a,g.mO);g.k=i2a.prototype;g.k.load=function(){g.mO.prototype.load.call(this);if(!O4(this)){var a=g.ZBa(this.player.getVideoData());a?(a=h2a(a,j2a(this)),P4(this,a,!1)):k2a(this)}};
g.k.unload=function(){P4(this,null);this.B&&(this.B.abort(),this.B=null);g.mO.prototype.unload.call(this)};
g.k.Fg=function(a,b){return O4(this)?"loadCustomEndscreenRenderer"===a?(a=h2a(b,"new"),P4(this,a),!0):null:null};
g.k.getOptions=function(){return O4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Bb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<C3a.length;f++){var h=Math.abs(b.width-C3a[f]);if(-1===e||d>=h)e=f,d=h}d=D3a[e];this.u&&g.El(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.F[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ol(e.element,m,f);g.Kl(e.element,n,p);this.ea&&(g.no(e.element,E3a),256<m||256<f?g.ko(e.element,"ytp-ce-large-round"):96<m||96<f?g.ko(e.element,"ytp-ce-medium-round"):g.ko(e.element,"ytp-ce-small-round"));g.no(e.element,F3a);m=h.left+h.width/2;h=h.top+l/2;g.ko(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.no(e.element,D3a);g.ko(e.element,d);(e=g.bh(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.El(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())T4(this,this.endscreen.impressionUrls),(a=g.wz())&&this.endscreen.visualElement&&g.Bz(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.F[a];g.ko(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.ko(b,"ytp-ce-shown");T4(this,c.impressionUrls);(b=g.wz())&&g.Bz(b,c.visualElement);this.player.V().F&&this.player.Pa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.mo(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.mo(b,"ytp-ce-shown");this.player.V().F&&this.player.Pa("endscreenelementhidden",a)}};
g.k.F4=function(a){var b=this;a.target===window&&(new g.bo(function(){for(var c=g.t(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.no(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var C3a=[346,426,470,506,570,640,853,1280,1920],D3a="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),F3a=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],E3a=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var x2a={sna:"current",dKa:"new"};var z2a={CLOSE:"close",DNa:"openUrl",SUBSCRIBE:"subscribe"},A2a={via:"click",CLOSE:"close",Rwa:"hidden",QSa:"rollOut",RSa:"rollOver",OUa:"shown"};C2a.prototype.Be=function(){var a=D2a(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var y3a={eea:"anchored",NU:"branding",CHANNEL:"channel",ina:"cta",Uwa:"highlightText",EAa:"label",PLAYLIST:"playlist",vQa:"popup",rXa:"speech",SUBSCRIBE:"subscribe",m_a:"title",VIDEO:"video",E5a:"website"},x3a={NU:"branding",zga:"card",rpa:"drawer",Twa:"highlight",eGa:"marker",vRa:"promotion",TEXT:"text",p6a:"widget"};g.v($4,g.M);g.k=$4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.kA(a,b,{id:c,namespace:"annotations_module"});d&&this.Ya.set(a,d);e&&this.eb.set(a,e);this.context.G.le([a])};
g.k.bB=function(){this.context.u.subscribe("resize",this.rC,this)};
g.k.YF=function(a,b,c,d,e,f){if(this.tb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.ph(this.element)};
g.k.rC=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=V4(a);if(f){var h=K2a(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.F||!1,n=g.vu(f||"");m&&n&&(n.v||n.list)?e.context.G.Yl(n.v,b,n.list,!1):g.pM(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m5(this.context.logger,c,l,d);J2a(f)||(c=g.wz(),d=b.itct,c&&d&&g.rK(c,g.pz(d)))}};
g.k.ra=function(){this.Ya.clear();this.eb.clear();g.M.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.N(this,a);return a.element};g.v(M2a,$4);g.k=M2a.prototype;g.k.oq=function(){this.oa&&e5(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Pl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.rC=function(){var a=this.isAvailable();g.Ql(this.element,a);g.O(this.context.G.getRootNode(),g.GT.IV_DRAWER_ENABLED,a);E4(this.G)};
g.k.destroy=function(){this.G.yx(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.Mx(this.ea);g.sx(this.ya);this.Ta&&this.Ta.dispose();this.F&&this.F.dispose();$4.prototype.destroy.call(this)};
g.k.iZ=function(){if(this.B){m5(this.context.logger,j5(this).tracking.close);var a=g.wz();a&&this.J&&g.rK(a,this.J);d5(this)}};
g.k.BZ=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.x0=function(){var a=g.wz(),b=j5(this);b=b?b.vf:this.vf;a&&b&&g.pK(a,[b])};
g.k.w0=function(){var a=g.wz(),b=j5(this);b=b?b.vf:this.vf;a&&b&&g.qK(a,[b])};
g.k.oV=function(){var a=j5(this);m5(this.context.logger,a.tracking.KT);var b=g.wz();b&&a&&g.pK(b,[a.Wj,a.vf])};
g.k.y0=function(){var a=g.wz(),b=j5(this);a&&b&&g.qK(a,[b.Wj])};
g.k.nV=function(a){var b=j5(this),c=g.wz();this.j?a?(a=this.context.logger,m5(a,b.tracking.mF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Wj&&g.rK(c,b.Wj)):(a=this.context.logger,m5(a,b.tracking.mF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.vf&&g.rK(c,b.vf)):(a=this.context.logger,m5(a,b.tracking.mF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.vf&&g.rK(c,this.vf))};g.v(k5,$4);k5.prototype.bB=function(){$4.prototype.bB.call(this);a3a(this)};
k5.prototype.show=function(){$4.prototype.show.call(this);var a=g.wz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.pK(a,[g.pz(b.itct)])};
k5.prototype.hide=function(){$4.prototype.hide.call(this);var a=g.wz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.qK(a,[g.pz(b.itct)])};g.v(l5,k5);
l5.prototype.show=function(){if(!this.isActive){k5.prototype.show.call(this);if(!this.J){g.ko(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({D:"img",Ga:["branding-img","iv-click-target"],X:{"aria-label":"\u983b\u9053\u6d6e\u6c34\u5370",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ql(this.u,!1);var b=this.createElement({D:"button",Ga:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=this.annotation.Be();c&&
a5(this,b,c,this.annotation.id,a.session_data);e3a(this,a);this.J=!0}g.Ql(this.element,!0);this.isActive=!0;this.u&&b3a(this,this.u)}};
l5.prototype.hide=function(){this.isActive&&(k5.prototype.hide.call(this),g.Ql(this.element,!1),this.isActive=!1)};
l5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);k5.prototype.destroy.call(this)};g.v(g3a,k5);g.k=g3a.prototype;g.k.show=function(){this.isActive||(k5.prototype.show.call(this),this.Z||(i3a(this),this.Z=!0),g.Ql(this.element,!0),g.Qh(function(){g.mo(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,m3a(this),j3a(this),k3a(this,this.I))};
g.k.hide=function(){this.isActive&&(g.ko(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.YF=function(a,b,c,d,e,f){return this.isCollapsed?!1:k5.prototype.YF.call(this,a,b,c,d,e,f)};
g.k.v_=function(a){this.S=!0;h3a(this,500,a)};
g.k.u_=function(){this.S=!1;l3a(this)};
g.k.p_=function(a){a.stopPropagation();this.hide()};
g.k.q_=function(a){a.stopPropagation();m3a(this);this.isCollapsed=!0;g.ko(this.element,"iv-promo-collapsed-no-delay");this.F.start()};
g.k.destroy=function(){this.F.dispose();k5.prototype.destroy.call(this)};g.v(o3a,g.mO);g.k=o3a.prototype;g.k.Fg=function(a,b){if(!B3a(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.wYa(b))&&s3a(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Q2a(this.j,b),E4(this.player)),!0}return null};
g.k.getOptions=function(){return B3a(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.ou=function(){var a=this.player.V(),b=this.player.getVideoData();return b.F&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.GM||a.oa.get(b.videoId)||g.pI(b)||g.qI(b)?!0:!1};
g.k.jE=function(){if(this.B){var a=this.player.gb().getVideoContentRect(!0);g.Ol(this.B.element,a.width,a.height);g.Kl(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Kk();a=this.j;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.k.pV=function(a){q3a(this,a.state);g.W(a.state,2)&&(this.Mi()&&this.Hm()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.yx(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Du(h)&&h.responseXML?h.responseXML:null)&&(s3a(b,h),g.ko(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.mO.prototype.load.call(this);q3a(this,this.player.Fb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Nv()&&(a=t3a(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().oa.get(d);f&&u3a(e,f);f=f&&(f.xC||f.Ty);if(!c.Gu||f)c.eb?this.C=g.Ju(c.eb,e):(this.Qn=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Qn));
g.IN(this.player,this.B.element,4);this.jE();(f=g.pI(c))&&z3a(this,f);(f=g.qI(c))&&f.featuredChannel&&A3a(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.eb&&(this.Qn&&(this.player.removeEventListener("videodatachange",this.Qn),this.Qn=null),this.C=g.Ju(b.eb,a))};
g.k.unload=function(){this.player.zf("annotations_module");for(var a=g.t(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,E4(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.mO.prototype.unload.call(this);this.B.detach();this.Qn&&(this.player.removeEventListener("videodatachange",this.Qn),this.Qn=null)};
g.k.tS=function(a){a===this.player.getVideoData().videoId&&(this.loaded?v3a(this):this.load())};
g.k.Mi=function(){return!!this.j&&this.j.isAvailable()};
g.k.Hm=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Mi();this.j&&(a?c?c5(this.j,c,b):c5(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):d5(this.j))};
g.k.yx=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.V().oa.unsubscribe("vast_info_card_add",this.tS,this);g.mo(this.player.getRootNode(),g.GT.IV_DRAWER_OPEN);for(var a=this.S,b=g.Yn,c=0,d=a.length;c<d;c++)b.Im(a[c]);this.S.length=0;g.mO.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.N(this,a);return a.element};g.lO("annotations_module",o3a);g.lO("creatorendscreen",i2a);})(_yt_player);
