(function(g){var window=this;'use strict';var H3a=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},I3a=function(a){return g.mG(a)&&!a.N("web_player_i_see_captions_3_killswitch")},J3a=function(a,b){var c=new g.IG;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},K3a=function(a,b){var c,d,e;
return g.A(function(f){if(1==f.j)return c=a+"|"+b,g.x(f,g.Iw(),2);if(3!=f.j){d=f.u;if(!d)throw g.iw("gct");return g.x(f,g.tH(d),3)}e=f.u;return f.return(e.get("captions",c))})},L3a=function(a,b,c){K3a(a,b).then(function(d){d&&c(d.trackData,new g.IG(d.metadata))})},O3a=function(a){if(!M3a.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(N3a,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},q5=function(){this.segments=[]},P3a=function(a,b){var c=g.mc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Zb(a.segments,c),g.Zb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.kc(a.segments,c,0,b),g.kc(a.segments,c+1,0,b)))},Q3a=function(a,b,c,d,e,f){g.M.call(this);
this.policy=a;this.player=b;this.ea=c;this.S=d;this.F=e;this.Z=f;this.Y=this.player.V();this.C=new q5;this.I=-1;this.B=this.u=this.j=null;this.J=new g.bo(this.dR,1E3,this);this.events=new g.VD(this);g.N(this,this.J);g.N(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.bx);this.bx();this.dR()},R3a=function(a){return a.j&&a.j.B?a.j.B+a.player.Ed()<a.player.getCurrentTime():!1},S3a=function(a,b){var c=g.nD(b,a.policy,{}).Be(),d={format:"RAW",
withCredentials:!0};a.policy.Ta&&(d.method="POST",d.postBody=b.Ys()||(0,g.mV)([120,0]));a.F&&(d.responseType="arraybuffer");a.B=g.Mu(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.F?e.response:e.responseText)||400<=e.status,h=g.Nxa(e);if(h){e=g.nD(a.u,a.policy,{});a.u.Lk(e,h);S3a(a,a.u);break a}f?a.player.va("capfail",{status:e.status}):(a.player.Ui().wh("fcb_r"),h=a.u.j[0].Na,null!=a.S&&a.I!==h&&(f=a.u.j[0],a.F?a.S(e.response,1E3*(f.startTime+a.player.Ed())):a.S(e.responseText,
1E3*(f.startTime+a.player.Ed())),a.I=h))}a.u=null;a.B=null}}).uj(function(e){a.u=null;
a.B=null;var f;a.player.va("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;P3a(a.C,a.u.j[0].Na)},r5=function(a,b){g.pO.call(this,b.V());
this.u=a;this.G=b;this.B=null;this.F=!1;this.I=g.oG(this.G.V())&&!this.u.isManifestless},U3a=function(a,b){var c=[],d;
for(d in a.u.j)if(a.u.j.hasOwnProperty(d)){var e=a.u.j[d];if(g.sO(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.I1a.get(e);null==n&&(n=T3a[e]||T3a[e.replace(/-/g,"_")],g.I1a.set(e,n));h=n||h}c.push(new g.IG({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},V3a=function(a,b){return null!=b&&b in a.u.j?a.u.j[b]:null},W3a=function(a,b,c){var d=
[],e;
for(e in a.u.j)if(a.u.j.hasOwnProperty(e)){var f=a.u.j[e];if(g.sO(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},s5=function(a,b,c,d,e,f,h,l){var m={};
Object.assign(m,b);Object.assign(m,a.params);Object.assign(m,c);var n={};Object.assign(n,b.Yd);a.params.Yd&&Object.assign(n,a.params.Yd);Object.assign(n,c.Yd);m.Yd=n;g.X.call(this,{D:"div",K:"caption-window",X:{id:"caption-window-"+a.id,dir:1===m.uh?"rtl":"ltr",tabindex:"0",lang:m.lang},W:[{D:"span",K:"captions-text",X:{style:"word-wrap: normal; display: block;"}}]});this.F=[];this.Ba=!1;this.u=a;this.La=this.Ia=null;this.playerWidth=f;this.playerHeight=h;this.I=null;this.maxWidth=.96*f;this.Ya=.96*
h;this.j=m;this.Wb=c;this.ea=b;this.C=this.Da("captions-text");this.Ab=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.oa=e/360*16;!l.kb("web_player_scale_font_size_for_shorts_killswitch")&&e>=d&&(this.oa=f/640*16);this.type=0;this.eb=this.oa*X3a(n);a=new g.bz(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.sV,this);a.subscribe("dragmove",this.rV,this);a.subscribe("dragend",this.qV,this);this.ob=this.jb=
0;b="";this.j.windowOpacity&&(a=O3a(this.j.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");a={"background-color":b,display:!1===this.j.isVisible?"none":"","text-align":Y3a[this.j.textAlign]};this.Ab&&(a["border-radius"]=b?this.eb/8+"px":"");if(this.B=2===this.u.params.uh||3===this.u.params.uh)b=this.element,c="vertical-rl",1===this.j.SL&&(c="vertical-lr"),g.Dc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.El(b,"-o-writing-mode",c),g.El(b,"-webkit-writing-mode",c),g.El(b,"writing-mode",
c),g.El(b,"text-orientation","upright"),g.ko(b,"ytp-vertical-caption"),3===this.u.params.uh&&(g.El(b,"text-orientation",""),g.El(b,"transform","rotate(180deg)"));g.El(this.element,a);switch(this.j.Ck){case 0:case 1:case 2:g.ko(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.ko(this.element,"ytp-caption-window-bottom")}},X3a=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Z3a=function(a,b){var c={},d=b.background?b.background:a.j.Yd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Yd.backgroundOpacity;d=O3a(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ab&&(c["box-decoration-break"]="clone",c["border-radius"]=a.eb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.oa*X3a(b)+"px";d=1;e=b.color||a.j.Yd.color;if(b.color||null!=b.textOpacity)e=O3a(e),d=null==b.textOpacity?a.j.Yd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.wH&&(h=e=b.wH);var l=a.oa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Xu()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Yd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.P_&&(c.visibility="hidden");1===b.zQ&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.sG||g.gw,3===a.u.params.uh?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Sl||2===b.Sl||3===b.Sl||4===b.Sl||5===b.Sl)if(g.sG)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Sl){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},$3a=function(a){a.I=g.lh("SPAN");
g.El(a.I,{display:"block"});g.ko(a.I,"caption-visual-line");a.C.appendChild(a.I)},a4a=function(a,b){var c=g.lh("SPAN");
g.El(c,{display:"inline-block","white-space":"pre-wrap"});g.El(c,Z3a(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.El(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.El(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},b4a=function(a,b,c){a.Ba=a.Ba||!!c;
var d={};Object.assign(d,a.j.Yd);Object.assign(d,c||b.j);Object.assign(d,a.Wb.Yd);(c=!a.I)&&$3a(a);for(var e=a.Ia&&a.La&&g.Ff(d,a.La)?a.Ia:a4a(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?($3a(a),e=a4a(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.mh(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.sG||!g.Gl(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Gl(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.df?g.El(e,m,"1em"):g.El(e,m,"0.5em")))}a.La=d;a.Ia=e;a.F.push(b)},t5=function(a,b,c,d){g.pO.call(this,a);
this.videoData=b;this.audioTrack=c;this.Va=d;this.C=b.uH},u5=function(a,b,c,d,e,f,h,l){s5.call(this,a,b,c,d,e,f,h,l);
this.type=1},v5=function(a,b,c,d,e,f,h,l){s5.call(this,a,b,c,d,e,f,h,l);
this.type=2;this.J=[];this.Z=this.S=this.Qa=0;this.ya=NaN;this.tb=0;this.Nb=null;this.Ta=new g.bo(this.J3,433,this);g.ko(this.element,"ytp-caption-window-rollup");g.N(this,this.Ta);g.El(this.element,"overflow","hidden")},c4a=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.SL&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},d4a=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.ep,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.S=d;b=Math;c=b.max;isNaN(a.ya)&&((d=a.j.Pp)?(e=g.lh("SPAN"),g.sh(e,"\u2013".repeat(d)),g.El(e,Z3a(a,a.j.Yd)),a.C.appendChild(e),a.ya=e.offsetWidth,a.C.removeChild(e)):a.ya=0);d=a.C;a.Z=c.call(b,a.ya,a.tb,(a.B?d.offsetHeight:d.offsetWidth)+1)},e4a=function(a,b){d4a(a);
var c=a.J.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.S-c;if(c!==a.Qa){var d=0<c&&0===a.Qa;b||isNaN(c)||d||(g.ko(a.element,"ytp-rollup-mode"),g.co(a.Ta));g.El(a.C,"transform",c4a(a,c));a.Qa=c}d4a(a)},w5=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.kA.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},x5=function(a,b,c,d,e){g.kA.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},f4a=function(a){var b="_"+y5++;
return new x5(0,0x8000000000000,0,b,a)},h4a=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.mf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=g4a(l.textContent,n.textContent,p.textContent,f.textContent,h);return new w5(a,b,e,c,l,d,m)}switch(m.mf){case 9:case 10:m.Sl=1;break;case 11:m.Sl=2;break;case 12:m.Sl=3;break;case 13:m.Sl=4;break;case 14:m.Sl=5}return new w5(a,b,e,c,l.textContent||"",d,m)},g4a=function(a,b,c,d,e){var f=g.Xu(),h=
f?g.lh("DIV"):g.lh("RUBY"),l=g.lh("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.lh("DIV"):g.lh("RP");a.textContent=b;h.appendChild(a);b=f?g.lh("DIV"):g.lh("RT");b.textContent=c;h.appendChild(b);c=e.mf;if(10===c||11===c||12===c||13===c||14===c)if(g.El(b,"text-emphasis-style","filled circle"),g.El(b,"text-emphasis-color","currentcolor"),g.El(b,"webkit-text-emphasis","filled circle"),11===e.mf||13===e.mf)g.El(b,"webkit-text-emphasis-position","under left"),g.El(b,"text-emphasis-position","under left");c=!0;if(4===e.mf||7===e.mf||12===e.mf||
14===e.mf)g.El(h,"ruby-position","over"),g.El(h,"-webkit-ruby-position","before");else if(5===e.mf||6===e.mf||11===e.mf||13===e.mf)g.El(h,"ruby-position","under"),g.El(h,"-webkit-ruby-position","after"),c=!1;e=f?g.lh("DIV"):g.lh("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.El(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.El(f,"display","none"),f=f.nextElementSibling,g.El(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.El(h.lastElementChild,"display","none"),d?(g.El(h,"padding-top","0.6em"),g.El(f,"top","0")):(g.El(h,"padding-bottom","0.6em"),g.El(f,"bottom","0")));return h},z5=function(){g.M.apply(this,arguments)},A5=function(a){z5.call(this);
this.C=a;this.pens={};this.S={};this.Z={};this.F="_"+y5++;this.J={};this.B=this.j=null;this.I=!0},B5=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},C5=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},D5=function(a,b){a=B5(a,b);
return void 0!==a?a:null},F5=function(a,b){a=a.getAttribute(b);
if(null!=a)return E5.test(a),a},i4a=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=D5(b,"mh");null!=a&&(c.Yw=a);a=D5(b,"ju");null!=a&&(c.textAlign=a);a=D5(b,"pd");null!=a&&(c.uh=a);a=D5(b,"sd");null!=a&&(c.SL=a);a=F5(b,"wfc");null!=a&&(c.windowColor=a);b=B5(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},j4a=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.S[d]);a=D5(b,"ap");null!=a&&(c.Ck=a);a=B5(b,"cc");null!=a&&(c.Pp=a);a=B5(b,"ah");null!=a&&(c.dj=a);a=B5(b,"rc");null!=a&&(c.ep=a);b=B5(b,"av");null!=b&&(c.Tl=b);return c},k4a=function(a,b,c,d){var e={};
Object.assign(e,j4a(a,b));Object.assign(e,i4a(a,b));d?g.Ff(e,a.C)?(d=a.F,e=a.C):d="_"+y5++:d=b.getAttribute("id")||"_"+y5++;a=B5(b,"t")+c;b=B5(b,"d")||0x8000000000000;if(2===e.uh||3===e.uh)c=e.ep,e.ep=e.Pp,e.Pp=c;return new x5(a,b,0,d,e)},G5=function(a){z5.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.F=new Map;this.B=new Map},H5=function(a){a=g.Hg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},l4a=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.F.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.ep=a);b=b.ccColCount;void 0!==b&&(f.Pp=b);if(2===f.uh||3===f.uh)b=f.ep,f.ep=f.Pp,f.Pp=b;return new x5(c,d,0,e,f)},n4a=function(){this.B=this.time=this.mode=this.u=0;
this.C=new m4a(this);this.F=new m4a(this);this.j=[];this.clear()},p4a=function(a,b,c){if(255===a&&255===b||!a&&!b)return{xs:a,
Lp:b,result:0};a=o4a[a];b=o4a[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Lp===d;if(d)return{xs:a,Lp:b,result:1}}else if(b&128&&1<=a&&31>=a)return{xs:a,Lp:b,result:2};return{xs:a,Lp:b,result:3}},r4a=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.F.u.clear()):(a.B=0,q4a(a.C,b,c,d))},s4a=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.t(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?r4a(a,d.XO,d.YO,b):1===d.type&&a.u&496&&q4a(a.F,d.XO,d.YO,b);a.j.length=0},I5=function(){this.type=0},J5=function(){this.state=this.Lp=this.xs=0},t4a=function(){this.timestamp=this.j=0},K5=function(a){this.F=a;
this.B=[];this.j=this.u=this.row=0;this.style=new I5;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new t4a}},L5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.F.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.F.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},y4a=function(a,b){switch(a){case 0:return u4a[(b&127)-32];
case 1:return v4a[b&15];case 2:return w4a[b&31];case 3:return x4a[b&31]}return 0},M5=function(a){return a.B[a.row][a.u]},N5=function(a,b,c){2<=b&&1<a.u&&(--a.u,M5(a).j=0);
var d=M5(a);d.timestamp=a.F.time+0;d.j=y4a(b,c);32>a.u&&a.u++},z4a=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},O5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},A4a=function(a){a.row=0<a.j?a.j:1;
a.u=1;O5(a,0,15)},B4a=function(a){this.B=a;
this.F=0;this.style=new I5;this.I=new K5(this.B);this.J=new K5(this.B);this.text=new K5(this.B);this.u=this.I;this.C=this.J;this.j=this.u},C4a=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(L5(d,c),A4a(a.u),A4a(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(L5(d,c),O5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},D4a=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},E4a=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},m4a=function(a){this.j=a;
this.F=0;this.B=new B4a(this.j);this.I=new B4a(this.j);this.u=new J5;this.C=this.B},q4a=function(a,b,c,d){a.u.update();
b=p4a(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.xs;c=b.Lp;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&N5(a,0,b),c&96&&N5(a,0,c),0!==b&&0!==c&&3===a.style.type&&L5(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.xs=e,b.Lp=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.F<<2)+(b.F<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.F<<2)+(b.F<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;z4a(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));O5(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:N5(b.j,0,32);break a;case 48:57===c?(d=b.j,M5(d).j=0,32>d.u&&d.u++):N5(b.j,1,c&15)}break;case 2:c&32&&N5(b.j,2,c&31);break;case 3:c&32&&N5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:D4a(b);
break;case 33:d=b.j;1<d.u&&(--d.u,M5(d).j=0);break;case 36:d=b.j;b=M5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:C4a(b,2,d);break;case 38:C4a(b,3,d);break;case 39:C4a(b,4,d);break;case 40:N5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);A4a(d);E4a(b);break;case 43:E4a(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:L5(a,d)}O5(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;L5(a,d);z4a(a,b,b+1,a.j-1);O5(a,a.row,1)}break;case 46:O5(b.C,0,15);break;case 47:L5(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,D4a(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},F4a=function(){},P5=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.F=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},Q5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},R5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},S5=function(a,b){z5.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new n4a;this.j.u=1<<this.track},H4a=function(a){if("string"===typeof a)return!1;
a=new P5(a,8,0);return G4a(a)},G4a=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==R5(a))return!1;
a.version=Q5(a);if(1<a.version)return!1;Q5(a);Q5(a);Q5(a);return!0},T5=function(){z5.call(this)},I4a=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new w5(b,c,d,e.id,p.nodeValue,f||0<n,g.Bf(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);I4a(a,b,c,d,e,!0,p,q,m)}}},J4a=function(a){var b=a.split(":");
a=0;b=g.t(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},K4a=function(a,b,c,d){d=Object.assign({Yw:0},d);
return new x5(a,b,c,"_"+y5++,d)},U5=function(a,b){g.M.call(this);
this.G=a;this.Y=b;this.parser=null;this.j=this.G.Cw()},Q4a=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=L4a(a,b,d),l=[];try{for(var m=g.t(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,r=p.IL;l="string"!==typeof q?l.concat(M4a(a,c,q,r,f)):"WEBVTT"===q.substring(0,6)?l.concat(N4a(a,q,r)):l.concat(O4a(a,c,q,r))}var w=l}catch(y){g.lz(y),a.clear(),w=[]}if(0!==w.length)return w}b=P4a(b);if(!b)return[];try{return"string"!==typeof b?M4a(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?N4a(a,b,d):O4a(a,c,b,d)}catch(y){return g.lz(y),a.clear(),[]}},P4a=function(a){if("string"===
typeof a||H4a(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.nC(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.ZB(a)},L4a=function(a,b,c){if("string"===typeof b||H4a(b))return[{trackData:b,
IL:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.Cwa(d);if(a.j&&e){var f=g.uwa(e),h=g.vwa(e);e=e.j;f&&e&&a.j.uB(e,f,h)}f=g.wC(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.t(f.entries());for(h=f.next();!h.done;h=f.next())e=g.t(h.value),h=e.next().value,e=e.next().value,e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.ZB(e),a.push({trackData:e,IL:c+1E3*h});R4a(d,a,c);return a=a.filter(function(l){return!!l.trackData})},
R4a=function(a,b,c){var d=g.nC(a,0,1836476516),e=9E4;
d&&(e=g.oC(d)||9E4);d=0;var f=g.wC(a,1836019558);f=g.t(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.t(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.nC(a,l.dataOffset,1953653094))&&(l=g.nC(a,l.dataOffset,1952867444))&&(l=g.uC(l)/e*1E3,0===h&&(d=l),b[h].IL=l-d+c||c*h*1E3)}},M4a=function(a,b,c,d,e){if(!H4a(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new S5(e,b));return a.parser.u(c,d)},N4a=function(a,b,c){a.parser||(a.parser=new T5);
a=a.parser.u(b,c);.01>Math.random()&&g.mz(Error("Deprecated subtitles format in web player: WebVTT"));return a},O4a=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new G5(S4a(b))),a.parser.u(c,d)}catch(f){return g.lz(f),[]}var e=g.wYa(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new A5(S4a(b),a.Y)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},S4a=function(a){var b=
{};
if(a=g.LG(a))b.lang=a,g.MZa.test(a)&&(b.uh=1);return b},V5=function(a){g.mO.call(this,a);
var b=this;this.G=a;this.Y=this.G.V();this.videoData=this.G.getVideoData();this.ob=this.G.gb();this.B={Yd:{}};this.F={Yd:{}};this.xa=[];this.S={};this.La={};this.ea=!1;this.Wb=g.xI(this.videoData);this.eb=g.GHa(this.videoData,this.G);this.Nb=!!this.videoData.captionTracks.length;this.kc=!!this.videoData.Kd;this.Qa="3"===this.Y.controlsType;this.u=this.I=this.J=this.Ia=this.jb=null;this.Ta=new U5(this.G,this.Y);this.j=null;this.oa=new g.VD(this);this.Ya=new g.X({D:"div",K:"ytp-caption-window-container",
X:{id:"ytp-caption-window-container"}});var c=null,d=g.So("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Go(d));this.storage=c;var e;this.tb=!(null==(e=a.Vd())||!e.kB());this.C=T4a(this);this.Z=!this.C&&this.Qa&&this.tb&&this.eb;g.N(this,this.Ta);this.C?this.Ba=this.ya=null:(this.ya=new g.$n(this.mM,void 0,this),g.N(this,this.ya),this.Ba=new g.bo(this.l5,2E3,this),g.N(this,this.Ba));g.N(this,this.oa);this.Y.N("caption_window_container_killswitch")||g.IN(this.player,this.Ya.element,4);
g.N(this,this.Ya);this.C||this.oa.T(a,"resize",this.pM);(this.Ab=(this.Y.N("web_player_track_tag_only_on_fullscreen_for_mweb_killswitch")||g.RF(this.Y))&&!g.Ry()&&!this.G.isFullscreen()&&!this.C&&!this.Z)&&this.oa.T(a,"resize",this.O2);this.oa.T(a,"onPlaybackAudioChange",this.U1);this.oa.T(a,g.mA("captions"),function(f){b.onCueRangeEnter(f)});
this.oa.T(a,g.nA("captions"),function(f){b.onCueRangeExit(f)});
U4a(this,V4a(this)||{})},Z4a=function(a){if(1===a.Y.jb||1===a.videoData.pJ||"alwayson"===g.hI(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.Y.jb){var c;g.qG(a.Y)?c=W4a(a):c=X4a(a,"module-enabled");if(null!=c)return!!c}c=H3a(a.player.getAudioTrack(),I3a(a.Y));var d=g.hI(a.videoData,"yt:cc");if(void 0===Y4a(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===g.hI(a.videoData,"yt:cc")},W5=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},Y4a=function(a){var b=void 0,c=g.Bv(g.Av.getInstance(),65);
if(g.qG(a.Y)&&null!=c){if(null!=W4a(a))return!1;b=!c}return b},$4a=function(a){var b;
a.Wb?b=new t5(a.Y,a.videoData,a.player.getAudioTrack(),a.player):a.eb?b=new r5(a.videoData.j,a.player):a.Nb?b=new g.qO(a.Y,a.videoData,a.player.getAudioTrack()):b=new g.tO(a.Y,a.videoData.Kd,a.videoData.videoId,g.dCa(a.videoData),a.videoData.mm);return b},Y5=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.kc?!1:a.Nb?!1:!0);a.Y.N("web_player_should_honor_include_asr_setting")&&g.mG(a.Y)&&(b=b||!!g.Bv(g.Av.getInstance(),66));b=g.nO(a.u.j,b);for(var c=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.hI(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.LG(b[e])===c[d])return b[e];return a.I&&a.I.B?a.I.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||X5(a)}return null},X5=function(a){return a.I&&a.I.j},Z5=function(a){var b=X5(a);
return!!b&&a.j===b},a5a=function(a){g.nO(a.u.j,!0);
var b=H3a(a.player.getAudioTrack(),I3a(a.Y)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=Y5(a,a.ea):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&W5(a)?c=X5(a):Y4a(a)||a.ea||Z4a(a)?c=Y5(a,a.ea):W5(a)&&(c=X5(a));if(a.C||a.Z){var d=g.nO(a.u.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.lh("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.JG(f));h.setAttribute("srclang",g.LG(f));h.setAttribute("id",f.toString());a.Z||h.setAttribute("src",a.u.Xs(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.G.Vd();c.My(b);c=c.Bf();a.tb&&a.oa.T(c.textTracks,"change",a.s4)}else!a.j&&c&&$5(a,c),a.player.Pa("onCaptionsTrackListChanged"),a.player.Pa("onApiChange")},b5a=function(a,b){var c=a.G.Vd().Bf().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},$5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ea=c,a.ea&&(g.qG(a.Y)?a6(a,!!b):b6(a,"module-enabled",!!b)));a.j=b;W5(a)&&(a.j=X5(a));a.load()},d5a=function(a,b){if(b instanceof x5){var c=a.S[b.id];
c&&c.u!==b&&(c.dispose(),delete a.S[b.id],c=null);c||(c=c5a(a,b))&&(a.S[b.id]=c)}else c=b.windowId,a.La[c]||(a.La[c]=[]),a.La[c].push(b)},e5a=function(a,b){a.Y.N("caption_window_container_killswitch")?g.IN(a.player,b,4):a.Ya.element.appendChild(b)},c5a=function(a,b){var c=a.ob.getVideoContentRect(!0).height,d=a.ob.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.LG(a.j):null;e&&g.MZa.test(e)&&(b.params.uh=1);e=a.ob.getPlayerSize();a.Y.N("web_player_caption_stickiness_for_glive_killswitch")||"google-live"!==a.Y.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.Yw?b.params.Yw:1<b.j.length?1:0){case 1:return new u5(b,a.B,a.F,d,c,e.width,e.height,a.Y.experiments);case 2:return new v5(b,a.B,a.F,d,c,e.width,e.height,a.Y.experiments);default:return new s5(b,a.B,a.F,d,c,e.width,e.height,a.Y.experiments)}},
U4a=function(a,b,c){c=void 0===c?!1:c;
var d=c6.Yd;a.B={};Object.assign(a.B,c6);a.B.Yd={};Object.assign(a.B.Yd,d);a.F={Yd:{}};var e=b.backgroundOverride?a.F:a.B,f=b.background||d.background;E5.test(f);e.Yd.background=f;e=b.colorOverride?a.F:a.B;f=b.color||d.color;E5.test(f);e.Yd.color=f;e=b.windowColorOverride?a.F:a.B;f=b.windowColor||c6.windowColor;E5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Yd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Yd.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Yd;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.F:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Yd.textOpacity=f;e=b.windowOpacityOverride?a.F:a.B;f=b.windowOpacity;null==f&&(f=c6.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.F:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Yd.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Yd.fontFamily=f;a.loaded&&a.pM();c&&(a.Y.N("web_player_local_storage_for_captions_setting_killswitch")?b6(a,"display-settings",b):g.Iz("yt-player-caption-display-settings",b,2592E3))},g5a=function(a,b,c){b&&!a.J?(b=f4a({uh:0,
lang:"zh-TW"}),a.J=[b,new w5(b.start,b.end-b.start,0,b.id,null!=c?c:"\u5b57\u5e55\u5916\u89c0\u7bc4\u4f8b")],a.player.le(a.J)):!b&&a.J&&(f5a(a,a.J),a.J=null)},f5a=function(a,b){a.player.qh(b);
b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.$b(a.xa,c.value);g.ao(a.ya)},X4a=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},b6=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},a6=function(a,b){a.G.isInline()||g.Iz("yt-player-sticky-caption",b,2592E3)},W4a=function(a){if(!a.G.isInline())return g.Jz("yt-player-sticky-caption")},V4a=function(a){return a.Y.N("web_player_local_storage_for_captions_setting_killswitch")?X4a(a,"display-settings"):g.Jz("yt-player-caption-display-settings")},T4a=function(a){var b,c=!(null==(b=a.G.Vd())||!b.jB());
return a.Qa&&c&&!a.eb};
g.TS.prototype.wz=g.ca(37,function(a){var b=2;this.La.has(a)?b=0:g.cLa(this,a)&&(b=1);return b});
g.MV.prototype.wz=g.ca(36,function(a){return this.rd.wz(a)});
g.TS.prototype.uB=g.ca(35,function(a,b,c){this.Ba.set(a,{Ls:b,Jy:c})});
g.MV.prototype.uB=g.ca(34,function(a,b,c){this.rd.uB(a,b,c)});
g.HO.prototype.Tv=g.ca(29,function(){for(var a=g.bh(document,"track",void 0,this.j),b=0;b<a.length;b++)g.ph(a[b])});
g.CS.prototype.Tv=g.ca(28,function(){this.mediaElement.Tv()});
g.HO.prototype.kB=g.ca(27,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.CS.prototype.kB=g.ca(26,function(){return this.mediaElement.kB()});
g.HO.prototype.jB=g.ca(25,function(){return!!this.j.textTracks});
g.CS.prototype.jB=g.ca(24,function(){return this.mediaElement.jB()});
g.HO.prototype.My=g.ca(23,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.CS.prototype.My=g.ca(22,function(a){this.mediaElement.My(a)});
g.pO.prototype.OK=g.ca(21,function(){return!1});
g.pO.prototype.Gq=g.ca(20,function(){});
g.qO.prototype.Gq=g.ca(19,function(a,b,c){var d=this;this.isDisposed();b=this.Xs(a,b);this.vp();this.u=g.Ju(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.tO.prototype.Gq=g.ca(18,function(a,b,c){var d=this;this.isDisposed();b=this.Xs(a,b);this.vp();this.u=g.Ju(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.AV.prototype.Iz=g.ca(8,function(){return this.J});
g.fY.prototype.Iz=g.ca(7,function(){var a;return(null==(a=g.wN(this))?void 0:a.Cw())||null});
g.BN.prototype.Cw=g.ca(6,function(){return this.app.Iz()});
g.GX.prototype.Cw=g.ca(5,function(){var a;return(null==(a=this.Ka)?void 0:a.Iz())||null});
var N3a=/#(.)(.)(.)/,M3a=/^#(?:[0-9a-f]{3}){1,2}$/i,T3a={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgn:"Western Balochi",bho:"Bhojpuri",
bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",
chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",
goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",
ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",
kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",
lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",
mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",
ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};q5.prototype.contains=function(a){a=g.mc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
q5.prototype.length=function(){return this.segments.length/2};
g.v(Q3a,g.M);g.k=Q3a.prototype;g.k.ra=function(){g.M.prototype.ra.call(this);this.B&&this.B.cancel()};
g.k.bx=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Ed();var b=this.j;this.j=g.Rb(this.ea.Tm(a).j);b!==this.j&&this.Z&&this.Z()};
g.k.reset=function(){this.C=new q5;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.dR=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Dp(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.By(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)if(b=this.player.Cw()){var c=a.j[0].j.info.id,d=a.j[0].Na,e=a.j[0].C;if(this.policy.Ta){if(b=b.Ys(e,d,c,3))a.S=b}else if(c=b.Qm(e,d,c,3))if(b=b.wz(d),0===b)c&&(a.B=new g.FB(c));else if(2===b){this.J.start();R3a(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.j[0].duration?(this.C.contains(a.j[0].Na)||S3a(this,a),this.j=g.Rb(a.j)):!this.Y.N("force_caption_seek_for_live_killswitch")&&R3a(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.v(r5,g.pO);g.k=r5.prototype;g.k.Gq=function(a,b,c){var d=this;this.vp();b=V3a(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?W3a(this,b,"386"):W3a(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.rO(this.Y);this.B=new Q3a(f,this.G,b,function(h,l){c(h,a,l,e)},this.I||g.BD(b.info),function(){d.B&&d.B.reset();
d.F=!0})}};
g.k.OK=function(){var a=this.F;this.F=!1;return a};
g.k.Uw=function(a){var b=this.I?[new g.IG({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.IG({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?U3a(this,"386"):U3a(this);b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.oO(this.j,c.value);a()};
g.k.vp=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Xs=function(){return""};
var E5=/^#(?:[0-9a-f]{3}){1,2}$/i;var Y3a=["left","right","center","justify"];g.v(s5,g.X);g.k=s5.prototype;g.k.sV=function(a,b){var c=g.Nl(this.element,this.element.parentElement);this.jb=a-c.x;this.ob=b-c.y;g.ko(this.element,"ytp-dragging")};
g.k.rV=function(a,b){var c=g.Pl(this.element);a=a-this.jb-.02*this.playerWidth;var d=b-this.ob-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Hg(e,0,2));var f=(d+c.height/2)/this.Ya*3;f=Math.floor(g.Hg(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Hg(a,0,1);c=(d+f/2*c.height)/this.Ya;c=100*g.Hg(c,0,1);this.u.params.Ck=b;this.u.params.Tl=c;this.u.params.dj=a;this.u.params.isDefault=!1;this.j.Ck=b;this.j.Tl=c;this.j.dj=a;this.j.isDefault=!1;this.ea.Ck=b;this.ea.Tl=c;
this.ea.dj=a;this.ea.isDefault=!1;this.dT()};
g.k.qV=function(){g.mo(this.element,"ytp-dragging")};
g.k.dT=function(){this.Ex(this.F)};
g.k.getType=function(){return this.type};
g.k.Ex=function(a){var b=Math.min(this.SP(),this.maxWidth),c=this.RP(),d="";3===this.u.params.uh&&(d="rotate(180deg)");g.El(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.gH(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.dj+2;d=this.j.Ck;switch(d){case 0:case 3:case 6:(b=this.j.Yd.fontSizeIncrement)&&0<b&&2!==this.j.uh&&3!==
this.j.uh&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.j.Tl+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.El(this.element,
a)};
g.k.gH=function(a){var b;for(b=0;b<a.length&&a[b]===this.F[b];b++);if(this.Ba||this.F.length>b)b=0,this.Ba=!1,this.F=[],this.I=this.La=this.Ia=null,g.nh(this.C);for(;b<a.length;b++)b4a(this,a[b])};
g.k.SP=function(){return 0};
g.k.RP=function(){return 0};
g.k.toString=function(){return g.X.prototype.toString.call(this)};g.v(t5,g.pO);t5.prototype.Gq=function(a,b,c){L3a(this.videoData.videoId,a.vssId,c)};
t5.prototype.Uw=function(a){if(this.audioTrack)for(var b=g.t(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.oO(this.j,c.value);a()};g.v(u5,s5);u5.prototype.gH=function(a){var b=this.u.j;s5.prototype.gH.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,h5a);var e=c.j;var f=d}b4a(this,c,d)}};
var h5a={P_:!0};g.v(v5,s5);g.k=v5.prototype;g.k.dT=function(){g.eo(this.Ta)};
g.k.J3=function(){g.mo(this.element,"ytp-rollup-mode");this.Ex(this.Nb,!0)};
g.k.RP=function(){return this.B?this.Z:this.S};
g.k.SP=function(){return this.B?this.S:this.Z};
g.k.Ex=function(a,b){this.Nb=a;if(this.u.params.ep){for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));this.tb=this.Z;this.S=this.Z=0;s5.prototype.Ex.call(this,a);e4a(this,b)}s5.prototype.Ex.call(this,a)};g.v(w5,g.kA);w5.prototype.toString=function(){return g.kA.prototype.toString.call(this)};g.v(x5,g.kA);x5.prototype.toString=function(){return g.kA.prototype.toString.call(this)};
var y5=0;g.v(z5,g.M);z5.prototype.u=function(){return[]};
z5.prototype.reset=function(){};g.v(A5,z5);A5.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
A5.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.t(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.t(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=C5(a,"b");
null!=l&&(h.bold=l);l=C5(a,"i");null!=l&&(h.italic=l);l=C5(a,"u");null!=l&&(h.underline=l);l=D5(a,"et");null!=l&&(h.charEdgeStyle=l);l=D5(a,"of");null!=l&&(h.offset=l);l=F5(a,"bc");null!=l&&(h.background=l);l=F5(a,"ec");null!=l&&(h.wH=l);l=F5(a,"fc");null!=l&&(h.color=l);l=D5(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=B5(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=B5(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=B5(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=D5(a,"rb");null!=l&&10!==l&&
0!==l&&(h.mf=10<l?l-1:l);a=D5(a,"hg");null!=a&&(h.zQ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=i4a(this,a);break;case "wp":c=a.getAttribute("id"),this.S[c]=j4a(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.t(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=k4a(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.F;
h=!!C5(a,"a");l=(B5(a,"t")||0)+l;var m=B5(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var r=0;r<q.length;r++){var w=q[r],y=void 0;0<r&&(h=!0);var z=void 0;1===w.nodeType&&(z=w);if(z&&"s"===z.tagName){if((w=(w=z.getAttribute("p"))?this.pens[w]:null)&&w.mf&&(1===w.mf?(w=q.slice(r,r+
4),4===w.length&&(y=h4a(l,m,f,h,n,w,this.pens),r+=3)):y=h4a(l,m,f,h,n,[z],this.pens)),!y){var B=z;y=l;z=m;w=f;var E=h,G=n,C=B.textContent?B.textContent:"",I=B.getAttribute("p");I=I?this.pens[I]:null;B=B5(B,"t")||0;y=new w5(y+B,z-B,G,w,C,E,I)}}else y=new w5(l,m,n,f,w.textContent||"",h,p);c.push(y);this.B=y}if(0<c.length)for(c[0].windowId===this.F&&(this.j=k4a(this,a,b,!0),d.push(this.j)),a=g.t(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var i5a=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(G5,z5);G5.prototype.reset=function(){this.B.clear()};
G5.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.t(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.wH=H5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=H5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=H5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.mf=10<h?h-1:h,f.Sl=i5a.get(f.mf));e.hgHorizGroup&&(f.zQ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.t(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.F.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Yw=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.uh=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.SL=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=H5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.F.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.t(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.dj=e.ahHorPos),void 0!==e.apPoint&&(f.Ck=e.apPoint),void 0!==e.avVerPos&&(f.Tl=e.avVerPos),void 0!==e.ccCols&&(f.Pp=e.ccCols),void 0!==e.rcRows&&(f.ep=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.t(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=l4a(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+y5++,h=l4a(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var r=p[l],w=r.utf8;if(w){var y=r.tOffsetMs||0,z=null;r.pPenId&&(z=this.j.get(r.pPenId));if(2===(null!=h.params.Yw?h.params.Yw:1<h.j.length?1:0)&&m&&"\n"===w)continue;if(r=z&&1===z.mf)if(r=l,r+3>=p.length||!p[r+1].pPenId||!p[r+2].pPenId||!p[r+3].pPenId)r=!1;else{var B=p[r+1].pPenId;(B=this.j.get(B))&&B.mf&&2===B.mf?(B=p[r+2].pPenId,B=this.j.get(B),!B||!B.mf||3>B.mf?r=!1:(B=p[r+3].pPenId,r=(B=this.j.get(B))&&
B.mf&&2===B.mf?!0:!1)):r=!1}if(r){y=p[l+1].utf8;r=p[l+3].utf8;B=p[l+2].utf8;var E=this.j.get(p[l+2].pPenId);w=g4a(w,y,B,r,E);m=new w5(d,e,n,f,w,m,z);l+=3}else m=new w5(d+y,e-y,n,h.id,w,m,z||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};n4a.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
n4a.prototype.reset=function(){this.mode=0;this.C.reset(0);this.F.reset(1)};
var o4a=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];I5.prototype.set=function(a){this.type=a};
I5.prototype.get=function(){return this.type};
J5.prototype.clear=function(){this.state=0};
J5.prototype.update=function(){this.state=2===this.state?1:0};
J5.prototype.isValid=function(){return 0!==this.state};
J5.prototype.matches=function(a,b){return this.isValid()&&a===this.xs&&b===this.Lp};
t4a.prototype.reset=function(){this.timestamp=this.j=0};
K5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
K5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
K5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var u4a=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],v4a=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],w4a=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],x4a=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];B4a.prototype.reset=function(a,b){this.F=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
m4a.prototype.reset=function(a){this.F=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};F4a.prototype.C=function(){};g.v(P5,F4a);P5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+y5++;c=c/1E3-this.I;d=d/1E3-this.I;a=new x5(c,d-c,5,f,{textAlign:0,Ck:0,dj:2.5*b,Tl:5.33*a});e=new w5(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.v(S5,z5);S5.prototype.u=function(a){a=new P5(a,a.byteLength,this.B);if(G4a(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=R5(a)*(1E3/45):1===a.version&&(a.B=4294967296*R5(a)+R5(a)),a.F=Q5(a);0<a.F;a.F--){var b=Q5(a),c=Q5(a),d=Q5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,XO:c,YO:d,order:b.j.length}))}s4a(this.j,a);return a.u}return[]};
S5.prototype.reset=function(){this.j.clear()};g.v(T5,z5);
T5.prototype.u=function(a,b){var c=[];a=a.split(j5a);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!k5a.test(e)){var h=l5a.exec(e);if(h&&4<=h.length){var l=J4a(h[1]),m=J4a(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,w="";n=g.t(n);for(var y=n.next();!y.done;y=n.next())if(y=y.value.split(":"),2===y.length){var z=y[1];switch(y[0]){case "line":y=z.split(",");y[0].endsWith("%")&&(p=y[0],h.Tl=Number.parseInt(p,10),2===y.length&&(q=y[1].trim()));break;case "position":y=
z.split(",");r=y[0];h.dj=Number.parseInt(r,10);2===y.length&&(w=y[1].trim());break;case "align":switch(z){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.dj=0;break;case 1:h.dj=100;break;case 2:h.dj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(w){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.Ck=q}e=e.substring(l5a.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=K4a(l,m,5,w),m=new w5(l,m,5,f.id,h,!1,g.Bf(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(m5a),1===q.length?(h=5,w=K4a(l,m,h,w)):(p=h=6,w=Object.assign({Pp:32},w),w=new x5(l,m,p,"_"+y5++,w)),c.push(w),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(y=g.wYa("<html>"+n+"</html>"),y.getElementsByTagName("parsererror").length?
(z=y.createElement("span"),z.appendChild(y.createTextNode(n))):z=y.firstChild,I4a(this,p,m-(p-l),h,w,0<r,z,e,c)):p=J4a(n)+f}l5a.lastIndex=0}}return c};
var k5a=/^NOTE/,j5a=/(?:\r\n|\r|\n){2,}/,l5a=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),m5a=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.ES.CD(T5,{u:"wvppt"});g.v(U5,g.M);U5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
U5.prototype.reset=function(){this.parser&&this.parser.reset()};
U5.prototype.ra=function(){g.M.prototype.ra.call(this);this.clear()};var c6={windowColor:"#080808",windowOpacity:0,textAlign:2,Ck:7,dj:50,Tl:100,isDefault:!0,Yd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(V5,g.mO);g.k=V5.prototype;g.k.ra=function(){if(this.C||this.Z){var a=this.G.Vd();a&&!a.isDisposed()&&a.Tv()}else g5a(this,!1);g.mO.prototype.ra.call(this)};
g.k.ou=function(){if(this.Qa)return this.C||this.Z;var a=H3a(this.player.getAudioTrack(),I3a(this.Y));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?W5(this):Y4a(this)||W5(this)?!0:Z4a(this)};
g.k.load=function(){var a=this;g.mO.prototype.load.call(this);var b=!this.Y.N("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.u?(this.j&&(this.Ta.clear(),this.C?b5a(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Gq(this.j,"json3",function(c,d,e,f){if(c){a.u.OK()&&(a.xa=[],a.G.zf("captions"),g.ao(a.ya),a.Ta.reset());c=Q4a(a.Ta,c,d,e,f);a.player.le(c,void 0,a.eb);if(!(!a.ea||a.Z||Z5(a)||g.cG(a.Y)||g.UF(a.Y))){g.fo(a.Ba);c=f4a({Ck:0,dj:5,Tl:5,
ep:2,textAlign:0,uh:0,lang:"zh-TW"});a.Ia=[c];e=["\u6309\u4e00\u4e0b "," \u9032\u5165\u8a2d\u5b9a"];a.jb||(f=new g.$K(g.rL()),g.N(a,f),a.jb=f.element);f=c.end-c.start;var h=g.JG(a.j);h&&a.Ia.push(new w5(c.start,f,0,c.id,h));a.Ia.push(new w5(c.start,f,0,c.id,e[0]),new w5(c.start,f,0,c.id,a.jb,!0),new w5(c.start,f,0,c.id,e[1],!0));a.player.le(a.Ia);g.co(a.Ba)}!a.ea||a.Z||Z5(a)||(g.qG(a.Y)?a6(a,!0):b6(a,"module-enabled",!0),a.I&&(a.I.C=a.j),a.player.Du());var l;null==(l=a.G.Lc())||l.va("cc",{kind:d.kind});
a.ea=!1}}),!b||this.C||this.Z||Z5(this)||this.player.Pa("captionschanged",g.KG(this.j))),b||(this.j&&!Z5(this)?this.player.Pa("captionschanged",g.KG(this.j)):this.player.Pa("onCaptionsTrackListChanged"))):(this.u=$4a(this),g.N(this,this.u),this.u.Uw(function(){a5a(a)}))};
g.k.unload=function(){this.C&&this.j?b5a(this,!1):(this.Ba&&g.fo(this.Ba),this.player.zf("captions"),this.xa=[],this.u&&this.u.vp(),this.Ta.clear(),this.J&&this.player.le(this.J),this.pM());g.mO.prototype.unload.call(this);this.player.Du();this.player.Pa("captionschanged",{})};
g.k.create=function(){this.ou()&&this.load()};
g.k.s4=function(){for(var a=this.G.Vd().Bf().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.nO(this.u.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.j:null)!==b&&$5(this,b,!0)};
g.k.c7=function(){!this.j&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.xa.push(a);g.ao(this.ya)};
g.k.onCueRangeExit=function(a){g.$b(this.xa,a);this.u instanceof r5&&this.u.I&&this.player.qh([a]);g.ao(this.ya)};
g.k.getCaptionWindowContainerId=function(){return this.Ya.element.id};
g.k.l5=function(){f5a(this,this.Ia);this.Ia=null};
g.k.mM=function(){var a=this;if(!this.Ab||!this.C){this.ya.stop();g.Cca(this.La);this.xa.sort(g.lA);var b=this.xa;if(this.J){var c=g.Bm(b,function(f){return-1===this.J.indexOf(f)},this);
c.length&&(b=c)}b=g.t(b);for(c=b.next();!c.done;c=b.next())d5a(this,c.value);b={};c=g.t(Object.entries(this.S));for(var d=c.next();!d.done;b={Jr:b.Jr,ql:b.ql},d=c.next()){var e=g.t(d.value);d=e.next().value;e=e.next().value;b.Jr=d;b.ql=e;this.La[b.Jr]?(b.ql.element.parentNode||(b.ql instanceof v5||b.ql instanceof u5||g.qf(this.S,function(f){return function(h,l){l!==f.Jr&&h.u.params.Ck===f.ql.u.params.Ck&&h.u.params.dj===f.ql.u.params.dj&&h.u.params.Tl===f.ql.u.params.Tl&&(h.dispose(),delete a.S[l]);
return l===f.Jr}}(b),this),e5a(this,b.ql.element)),b.ql.Ex(this.La[b.Jr])):(b.ql.dispose(),delete this.S[b.Jr])}}};
g.k.r5=function(){U4a(this,{},!0);this.Y.N("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Pa("captionssettingschanged")};
g.k.l_=function(){var a=c6.Yd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:c6.windowColor,windowOpacity:c6.windowOpacity};var b=V4a(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.pU=function(a,b){var c={};Object.assign(c,V4a(this));Object.assign(c,a);U4a(this,c,b);this.player.Pa("captionssettingschanged")};
g.k.pM=function(){!this.C&&this.loaded&&(g.nf(this.S,function(a,b){a.dispose();delete this.S[b]},this),this.mM())};
g.k.Fg=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Hg(b,-2,4);this.pU({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&$5(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.Y.F&&(g.qG(this.Y)?a6(this,!!b):b6(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Na(b))break;if(g.Bf(b)){$5(this,null,!0);break}a=g.nO(this.u.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?J3a(e,b.translationLanguage):e)}!c||c===this.j&&this.loaded||(b=g.wya(),a=g.LG(c),b.length&&a===b[b.length-1]||(b.push(a),g.Iz("yt-player-caption-language-preferences",b)),$5(this,c,!0))}else return this.loaded&&this.j&&!Z5(this)?g.KG(this.j):{};return"";case "tracklist":return this.u?g.Uk(g.nO(this.u.j,!(!b||!b.includeAsr)),function(f){return g.KG(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||g5a(this,!!b);break;case "sampleSubtitlesCustomized":this.C||g5a(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.F&&a.push("stickyLoading");return a};
g.k.JI=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.Y.N("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.LG(a));return{cc:b}}return{}};
g.k.H6=function(){this.loaded&&this.j&&!Z5(this)?(g.qG(this.Y)?a6(this,!1):b6(this,"module-enabled",!1),this.unload(),W5(this,!0)&&$5(this,X5(this),!1)):this.ST()};
g.k.ST=function(){this.loaded&&this.j&&!Z5(this)||$5(this,Z5(this)||!this.j?Y5(this,!0):this.j,!0)};
g.k.U1=function(){var a=Z5(this);W5(this,a)?$5(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.ou()&&(a?$5(this,Y5(this),!1):this.load()))};
g.k.O2=function(){var a=this.G.Vd();a&&!a.isDisposed()&&a.Tv();this.G.isFullscreen()?(this.C=this.Qa=!0,this.loaded&&a5a(this)):(this.Qa="3"===this.Y.controlsType,this.C=T4a(this));$5(this,this.j)};
g.ES.CD(V5,{mM:"smucd"});g.lO("captions",V5);})(_yt_player);
