(function(g){var window=this;'use strict';var C5a=function(a,b){a.Pa("onAutonavCoundownStarted",b)},l6=function(a,b,c){g.O(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Rf(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.TG&&(b.lengthText?(e=b.lengthText||null,f=b.At||null):b.lengthSeconds&&(e=g.cM(b.lengthSeconds),f=g.cM(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.RG(d).type;var l=b instanceof g.TG?b.isLivePlayback:null,m=b instanceof g.TG?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],w=[];n&&r.push(n);p&&(r.push(p),w.push(p));q&&w.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.HJ("\u89c0\u770b\u300c$TITLE\u300d",{TITLE:b.title}),duration:e,timestamp:f,url:b.Xm(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:b.Kp};b instanceof g.SG&&(c.playlist_length=b.playlistLength);a.update(c)},m6=function(a){var b=a.V(),c=b.B;
g.X.call(this,{D:"a",K:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.S:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{D:"div",Ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},W:[{D:"div",X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{D:"div",Ga:["ytp-autonav-live-stamp"],qa:"\u76f4\u64ad"},
{D:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"\u5373\u5c07\u64ad\u51fa"},{D:"div",K:"ytp-autonav-list-overlay",W:[{D:"div",K:"ytp-autonav-mix-text",qa:"\u5408\u8f2f"},{D:"div",K:"ytp-autonav-mix-icon"}]}]},{D:"div",Ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],qa:"{{title}}"},{D:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],qa:"{{author}}"},{D:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],qa:"{{views_and_publish_time}}"}]});
this.G=a;this.suggestion=null;this.j=c;this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress)},n6=function(a,b){b=void 0===b?!1:b;
g.X.call(this,{D:"div",K:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.I=b;this.F=void 0;this.B=0;this.container=new g.X({D:"div",K:"ytp-autonav-endscreen-countdown-container"});g.N(this,this.container);this.container.Ca(this.element);b=a.V();var d=b.B;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.N("web_rounded_thumbnails")&&e.push("rounded-thumbnail");
this.j=new g.X({D:"div",K:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{D:"div",K:"ytp-autonav-endscreen-upnext-header"},{D:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",qa:"{{autoplayAlternativeHeader}}"},{D:"a",K:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.S:""},W:[{D:"div",Ga:e,X:{style:"{{background}}"},W:[{D:"div",
X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{D:"div",Ga:["ytp-autonav-live-stamp"],qa:"\u76f4\u64ad"},{D:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"\u5373\u5c07\u64ad\u51fa"}]},{D:"div",K:"ytp-autonav-endscreen-video-info",W:[{D:"div",K:"ytp-autonav-endscreen-premium-badge"},{D:"div",K:"ytp-autonav-endscreen-upnext-title",qa:"{{title}}"},{D:"div",K:"ytp-autonav-endscreen-upnext-author",qa:"{{author}}"},{D:"div",K:"ytp-autonav-view-and-date",qa:"{{views_and_publish_time}}"},
{D:"div",K:"ytp-autonav-author-and-view",qa:"{{author_and_views}}"}]}]}]});g.N(this,this.j);this.j.Ca(this.container.element);d||this.T(this.j.Da("ytp-autonav-endscreen-link-container"),"click",this.ZM);this.G.vb(this.container.element,this,115127);this.G.vb(this.j.Da("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.X({D:"div",K:"ytp-autonav-overlay"});g.N(this,this.overlay);this.overlay.Ca(this.container.element);this.u=new g.X({D:"div",K:"ytp-autonav-endscreen-button-container"});
g.N(this,this.u);this.u.Ca(this.container.element);this.cancelButton=new g.X({D:"button",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"\u53d6\u6d88\u81ea\u52d5\u64ad\u653e"},qa:"\u53d6\u6d88"});g.N(this,this.cancelButton);this.cancelButton.Ca(this.u.element);this.cancelButton.Ra("click",this.wV,this);this.G.vb(this.cancelButton.element,this,115129);this.playButton=
new g.X({D:"a",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"\u64ad\u653e\u4e0b\u4e00\u90e8\u5f71\u7247"},qa:"\u7acb\u5373\u64ad\u653e"});g.N(this,this.playButton);this.playButton.Ca(this.u.element);this.playButton.Ra("click",this.ZM,this);this.G.vb(this.playButton.element,this,115130);this.C=new g.bo(function(){D5a(c)},500);
g.N(this,this.C);this.YM();this.T(a,"autonavvisibility",this.YM);this.G.N("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.vV),this.T(a,"onAutonavCoundownStarted",this.V1))},o6=function(a){var b=a.G.Kk(!0,a.G.isFullscreen());
g.O(a.container.element,"ytp-autonav-endscreen-small-mode",a.Lg(b));g.O(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.iF);g.O(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.kf());g.O(a.G.getRootNode(),"countdown-running",a.Ij());g.O(a.container.element,"ytp-player-content",a.G.kf());g.El(a.overlay.element,{width:b.width+"px"});if(!a.Ij()){a.G.kf()?E5a(a,Math.round(F5a(a)/1E3)):E5a(a);b=!!a.suggestion&&!!a.suggestion.Kp;var c=a.G.kf()||!b;g.O(a.container.element,
"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.O(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.cL(a.u,a.G.kf());g.O(a.element,"ytp-enable-w2w-color-transitions",G5a(a))}},D5a=function(a){var b=F5a(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);E5a(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Ij()?a.select(!0):a.Ij()&&a.C.start()},F5a=function(a){if(a.G.isFullscreen()){var b;
a=null==(b=a.G.getVideoData())?void 0:b.yM;return-1===a||void 0===a?8E3:a}return 0<=a.G.eq()?a.G.eq():g.UE(a.G.V().experiments,"autoplay_time")||1E4},G5a=function(a){var b;
return!(null==(b=a.G.getVideoData())||!b.watchToWatchTransitionRenderer)},E5a=function(a,b){b=void 0===b?-1:b;
a=a.j.Da("ytp-autonav-endscreen-upnext-header");g.nh(a);if(0<=b){b=String(b);var c="\u4e0b\u4e00\u90e8\u5f71\u7247\u5c07\u5728 $SECONDS \u79d2\u5f8c\u64ad\u653e".match(RegExp("\\$SECONDS","gi"))[0],d="\u4e0b\u4e00\u90e8\u5f71\u7247\u5c07\u5728 $SECONDS \u79d2\u5f8c\u64ad\u653e".indexOf(c);if(0<=d){a.appendChild(g.mh("\u4e0b\u4e00\u90e8\u5f71\u7247\u5c07\u5728 $SECONDS \u79d2\u5f8c\u64ad\u653e".slice(0,d)));var e=g.lh("span");g.io(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.sh(e,b);
a.appendChild(e);a.appendChild(g.mh("\u4e0b\u4e00\u90e8\u5f71\u7247\u5c07\u5728 $SECONDS \u79d2\u5f8c\u64ad\u653e".slice(d+c.length)));return}}g.sh(a,"\u5373\u5c07\u64ad\u653e")},p6=function(a,b){g.X.call(this,{D:"div",
Ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},q6=function(a){g.X.call(this,{D:"div",
Ga:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},W:[{D:"div",K:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{D:"span",K:"ytp-upnext-top",W:[{D:"span",K:"ytp-upnext-header",qa:"\u5373\u5c07\u64ad\u653e"},{D:"span",K:"ytp-upnext-title",qa:"{{title}}"},{D:"span",K:"ytp-upnext-author",qa:"{{author}}"}]},{D:"a",K:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"\u64ad\u653e\u4e0b\u4e00\u90e8\u5f71\u7247"},W:[{D:"svg",X:{height:"100%",version:"1.1",
viewBox:"0 0 72 72",width:"100%"},W:[{D:"circle",K:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",K:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",K:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",K:"ytp-upnext-bottom",W:[{D:"span",K:"ytp-upnext-cancel"},
{D:"span",K:"ytp-upnext-paused",qa:"\u5df2\u66ab\u505c\u81ea\u52d5\u64ad\u653e\u529f\u80fd"}]}]});this.api=a;this.cancelButton=null;this.F=this.Da("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.bo(this.AC,5E3,this);this.u=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=new g.X({D:"button",Ga:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"\u53d6\u6d88\u81ea\u52d5\u64ad\u653e"},qa:"\u53d6\u6d88"});g.N(this,this.cancelButton);
this.cancelButton.Ra("click",this.xV,this);this.cancelButton.Ca(b);this.cancelButton&&this.api.vb(this.cancelButton.element,this,115129);g.N(this,this.C);this.api.vb(this.element,this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.T(b,"click",this.yV);this.api.vb(b,this,115130);this.aN();this.T(a,"autonavvisibility",this.aN);this.T(a,"mdxnowautoplaying",this.Q2);this.T(a,"mdxautoplaycanceled",this.R2);g.O(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},H5a=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.yM;return-1===a||void 0===a?8E3:a}return 0<=a.api.eq()?a.api.eq():g.UE(a.api.V().experiments,"autoplay_time")||1E4},I5a=function(a,b){b=H5a(a,b);
var c=Math,d=c.min;var e=(0,g.T)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.F.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Ij()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Ij()&&a.j.start()},r6=function(a){p6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.X({D:"div",K:"ytp-suggestion-panel",W:[{D:"div",Ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],qa:"\u66f4\u591a\u5f71\u7247"}]});this.J=new g.X({D:"div",K:"ytp-suggestions-container"});this.videos=[];this.B=null;this.F=this.I=!1;this.u=new n6(this.player);g.N(this,this.u);this.u.Ca(this.element);a.getVideoData().Je?this.j=this.u:(this.j=new q6(a),g.IN(this.player,this.j.element,4),g.N(this,this.j));this.overlay=new g.X({D:"div",
K:"ytp-autonav-overlay-cancelled-state"});g.N(this,this.overlay);this.overlay.Ca(this.element);this.C=new g.VD(this);g.N(this,this.C);g.N(this,this.table);this.table.Ca(this.element);this.table.show();g.N(this,this.J);this.J.Ca(this.table.element);this.hide()},s6=function(a){var b=a.kf();
b!==a.F&&(a.F=b,a.player.ma("autonavvisibility"),a.F?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},t6=function(a,b){g.X.call(this,{D:"button",
Ga:["ytp-watch-on-youtube-button","ytp-button"],X:{title:"{{message}}"},qa:"{{content}}"});this.G=a;this.buttonType=this.buttonType=b;switch(this.buttonType){case 1:a="\u5728 YouTube \u4e0a\u518d\u6b21\u89c0\u770b";b=156915;break;case 2:a="\u524d\u5f80 YouTube \u7e7c\u7e8c\u89c0\u770b";b=156942;break;default:a="\u524d\u5f80 YouTube \u7e7c\u7e8c\u89c0\u770b",b=156942}this.update({message:a,content:a});this.G.vb(this.element,this,b);this.Ra("click",this.onClick);g.cL(this,!0)},u6=function(a,b){p6.call(this,
a,"embeds-lite-endscreen");
this.G=a;this.j=b;this.G.vb(this.element,this,156943);this.watchButton=new t6(a,2);g.N(this,this.watchButton);this.watchButton.Ca(this.element);this.hide()},J5a=function(a){p6.call(this,a,"subscribecard-endscreen");
this.j=new g.X({D:"div",K:"ytp-subscribe-card",W:[{D:"img",K:"ytp-author-image",X:{src:"{{profilePicture}}"}},{D:"div",K:"ytp-subscribe-card-right",W:[{D:"div",K:"ytp-author-name",qa:"{{author}}"},{D:"div",K:"html5-subscribe-button-container"}]}]});g.N(this,this.j);this.j.Ca(this.element);var b=a.getVideoData();this.subscribeButton=new g.qP("\u8a02\u95b1",null,"\u53d6\u6d88\u8a02\u95b1",null,!0,!1,b.fl,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.subscribeButton);this.subscribeButton.Ca(this.j.Da("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ja);this.Ja();this.hide()},v6=function(a){var b=a.V(),c=g.YD||g.KF?{style:"will-change: opacity"}:void 0,d=b.B,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.X.call(this,{D:"a",Ga:e,X:{href:"{{url}}",target:d?b.S:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{D:"div",K:"ytp-videowall-still-image",X:{style:"{{background}}"}},{D:"span",K:"ytp-videowall-still-info",X:{"aria-hidden":"true"},W:[{D:"span",K:"ytp-videowall-still-info-bg",W:[{D:"span",K:"ytp-videowall-still-info-content",X:c,W:[{D:"span",K:"ytp-videowall-still-info-title",
qa:"{{title}}"},{D:"span",K:"ytp-videowall-still-info-author",qa:"{{author_and_views}}"},{D:"span",K:"ytp-videowall-still-info-live",qa:"\u76f4\u64ad"},{D:"span",K:"ytp-videowall-still-info-duration",qa:"{{duration}}"}]}]}]},{D:"span",Ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{D:"span",K:"ytp-videowall-still-listlabel-icon"},"\u64ad\u653e\u6e05\u55ae",{D:"span",K:"ytp-videowall-still-listlabel-length",W:[" (",{D:"span",qa:"{{playlist_length}}"},
")"]}]},{D:"span",Ga:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{D:"span",K:"ytp-videowall-still-listlabel-mix-icon"},"\u5408\u8f2f",{D:"span",K:"ytp-videowall-still-listlabel-length",qa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.VD(this);g.N(this,this.j);this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.Xg(this.element,this);this.onVideoDataChange()},
w6=function(a){p6.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.F=this.J=!1;this.S=null;this.u=new g.VD(this);g.N(this,this.u);this.Z=a.N("web_rounded_thumbnails");this.I=new g.bo(function(){g.ko(b.element,"ytp-show-tiles")},0);
g.N(this,this.I);var c=new g.X({D:"button",Ga:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"\u4e0a\u4e00\u90e8"},W:[g.hL()]});g.N(this,c);c.Ca(this.element);c.Ra("click",this.CV,this);this.table=new g.$K({D:"div",K:"ytp-endscreen-content"});g.N(this,this.table);this.table.Ca(this.element);c=new g.X({D:"button",Ga:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"\u4e0b\u4e00\u500b"},W:[g.iL()]});g.N(this,c);c.Ca(this.element);c.Ra("click",this.BV,this);a.getVideoData().Je?this.j=new n6(a,
!0):this.j=new q6(a);g.N(this,this.j);g.IN(this.player,this.j.element,4);a.vb(this.element,this,158789);this.hide()},x6=function(a){return g.JN(a.player)&&a.Oy()&&!a.C},K5a=function(a){var b,c,d,e;
return(null==(b=a.videoData)?0:null==(c=b.suggestions)?0:c.length)?null==(d=a.videoData)?void 0:d.suggestions:[null==(e=a.videoData)?void 0:g.RH(e)]},y6=function(a){var b=a.kf();
b!==a.J&&(a.J=b,a.player.ma("autonavvisibility"))},z6=function(a){p6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new t6(a,1);g.N(this,this.watchButton);this.watchButton.Ca(this.element);if(a.N("embeds_enable_shorts_branded_ui")){g.ko(this.element,"ytp-shorts-branded-ui");var b=new g.K2(a,g.yN(a));g.N(this,b);var c=new g.X({D:"div",Ga:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},W:[b]});g.N(this,c);b.Ca(c.element);c.Ca(this.element)}a.vb(this.element,this,156914);this.hide()},O5a=function(a){g.mO.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.VD(this);g.N(this,this.listeners);var c=a.V();if(g.tv(g.fG(c)))this.u=!0,this.endScreen=new u6(a,g.yN(a));else{var d;(null==(d=g.yN(a))?0:d.aj())?this.endScreen=new z6(a):L5a(a)?(this.C=!0,M5a(this),this.j?this.endScreen=new r6(a):this.endScreen=new w6(this.player)):c.Je?this.endScreen=new J5a(this.player):this.endScreen=new p6(this.player)}g.N(this,this.endScreen);g.IN(this.player,this.endScreen.element,4);N5a(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.mA("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.nA("endscreen"),function(e){b.onCueRangeExit(e)})},M5a=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.ll&&a.B===b.Je)return!1;a.j=b.ll;a.B=b.Je;return!0},L5a=function(a){a=a.V();
return a.Ec&&!a.Je},N5a=function(a){a.player.zf("endscreen");
var b=a.player.getVideoData();b=new g.kA(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.kA(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.le([b,c])};
g.qS.prototype.Ax=g.ca(33,function(a){this.DK!==a&&(this.DK=a,this.dk())});
g.pS.prototype.ip=g.ca(32,function(a){this.u!==a&&(this.u=a,this.Gy())});
g.qS.prototype.ip=g.ca(31,function(a){this.Ph&&this.Ph.ip(a)});
g.bP.prototype.aB=g.ca(30,function(a){this.EK!==a&&(this.EK=a,this.On())});
g.BN.prototype.eq=g.ca(4,function(){return this.app.eq()});
g.fY.prototype.eq=g.ca(3,function(){return this.getVideoData().SM});g.v(m6,g.X);m6.prototype.select=function(){(this.G.Yl(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.kz||void 0)||this.G.N("web_player_endscreen_double_log_fix_killswitch"))&&this.G.sb(this.element)};
m6.prototype.onClick=function(a){g.NO(a,this.G,this.j,this.suggestion.sessionData||void 0)&&this.select()};
m6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.yx(a)||(this.select(),g.xx(a))}};g.v(n6,g.X);g.k=n6.prototype;g.k.LB=function(a){this.suggestion!==a&&(this.suggestion=a,l6(this.j,a),this.playButton.Ma("url",this.suggestion.Xm()),o6(this))};
g.k.Ij=function(){return 0<this.B};
g.k.Ix=function(){this.Ij()||(this.B=Date.now(),D5a(this),C5a(this.G,F5a(this)),g.O(this.G.getRootNode(),"countdown-running",this.Ij()))};
g.k.Ot=function(){this.qp();D5a(this);var a=this.j.Da("ytp-autonav-endscreen-upnext-header");a&&g.sh(a,"\u5373\u5c07\u64ad\u653e")};
g.k.qp=function(){this.Ij()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.qp()};
g.k.ZM=function(a){g.NO(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.sb(this.playButton.element):a.currentTarget===this.j.Da("ytp-autonav-endscreen-link-container")&&(a=this.j.Da("ytp-autonav-endscreen-link-container"),this.G.Wa(a,!0),this.G.sb(a)),this.select())};
g.k.wV=function(){this.G.sb(this.cancelButton.element);g.DN(this.G,!0);this.F&&this.G.Pa("innertubeCommand",this.F)};
g.k.onVideoDataChange=function(a,b){var c;this.F=null==(c=b.hV)?void 0:c.command};
g.k.V1=function(a){if(G5a(this)){var b=this.G.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.nM(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.nM(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.nM(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.nM(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.nM(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.nM(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.O(this.element,"ytp-w2w-animate",!0)}};
g.k.vV=function(a){this.G.N("web_autonav_color_transition")&&2!==a&&g.O(this.element,"ytp-w2w-animate",!1)};
g.k.YM=function(){var a=this.G.kf();this.I&&this.rb!==a&&g.cL(this,a);o6(this);this.G.Wa(this.container.element,a);this.G.Wa(this.cancelButton.element,a);this.G.Wa(this.j.Da("ytp-autonav-endscreen-link-container"),a);this.G.Wa(this.playButton.element,a)};
g.k.Lg=function(a){return 400>a.width||459>a.height};g.v(p6,g.X);g.k=p6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Oy=function(){return!1};
g.k.kf=function(){return!1};
g.k.RQ=function(){return!1};g.v(q6,g.X);g.k=q6.prototype;g.k.AC=function(){this.notification&&(this.C.stop(),this.zc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.LB=function(a){this.suggestion=a;l6(this,a,"hqdefault.jpg")};
g.k.aN=function(){g.cL(this,this.api.kf());this.api.Wa(this.element,this.api.kf());this.api.Wa(this.Da("ytp-upnext-autoplay-icon"),this.api.kf());this.cancelButton&&this.api.Wa(this.cancelButton.element,this.api.kf())};
g.k.Z2=function(){window.focus();this.AC()};
g.k.Ix=function(a){var b=this;this.Ij()||(g.Nx("a11y-announce","\u5373\u5c07\u64ad\u653e "+this.suggestion.title),this.u=(0,g.T)(),this.j=new g.bo(function(){I5a(b,a)},25),I5a(this,a),C5a(this.api,H5a(this,a)));
g.mo(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.X.prototype.hide.call(this)};
g.k.Ij=function(){return!!this.j};
g.k.Ot=function(){this.qp();this.u=(0,g.T)();I5a(this);g.ko(this.element,"ytp-upnext-autoplay-paused")};
g.k.qp=function(){this.Ij()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.AC(),this.notification=new Notification("\u5373\u5c07\u64ad\u653e",{body:this.suggestion.title,icon:this.suggestion.Rf()}),this.B=this.T(this.notification,"click",this.Z2),this.C.start())}this.qp();this.api.nextVideo(!1,a)};
g.k.yV=function(a){!g.rh(this.cancelButton.element,g.tx(a))&&g.NO(a,this.api)&&(this.api.kf()&&this.api.sb(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.k.xV=function(){this.api.kf()&&this.cancelButton&&this.api.sb(this.cancelButton.element);g.DN(this.api,!0)};
g.k.Q2=function(a){this.api.getPresentingPlayerType();this.show();this.Ix(a)};
g.k.R2=function(){this.api.getPresentingPlayerType();this.qp();this.hide()};
g.k.ra=function(){this.qp();this.AC();g.X.prototype.ra.call(this)};g.v(r6,p6);g.k=r6.prototype;g.k.create=function(){p6.prototype.create.call(this);this.C.T(this.player,"appresize",this.oy);this.C.T(this.player,"onVideoAreaChange",this.oy);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.bN);this.C.T(this.player,"autonavcancel",this.zV);this.onVideoDataChange()};
g.k.show=function(){p6.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.DN(this.player,!1);g.JN(this.player)&&this.Oy()&&!this.B?(s6(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Ix():3===this.videoData.autonavState&&this.j.Ot()):(g.DN(this.player,!0),s6(this));this.oy()};
g.k.hide=function(){p6.prototype.hide.call(this);this.j.Ot();s6(this)};
g.k.oy=function(){var a=this.player.Kk(!0,this.player.isFullscreen());s6(this);o6(this.u);g.O(this.element,"ytp-autonav-cancelled-small-mode",this.Lg(a));g.O(this.element,"ytp-autonav-cancelled-tiny-mode",this.JD(a));g.O(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.El(this.overlay.element,{width:a.width+"px"});if(!this.F){a=g.t(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.t(b.value);b=c.next().value;c=c.next().value;g.O(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){var b=g.RH(this.videoData);b&&(this.j.LB(b),this.j!==this.u&&this.u.LB(b));for(b=0;b<P5a.length;++b){var c=P5a[b];if(a&&a[c]){this.videos[b]=new m6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,l6(d,c));g.N(this,this.videos[b]);this.videos[b].Ca(this.J.element)}}}this.oy()}};
g.k.bN=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.qp(),this.rb&&this.oy()):(this.I=!0,this.kf()&&(2===a?this.j.Ix():3===a&&this.j.Ot()))};
g.k.zV=function(a){a?this.bN(1):(this.B=null,this.I=!1)};
g.k.Oy=function(){return 1!==this.videoData.autonavState};
g.k.Lg=function(a){return(910>a.width||459>a.height)&&!this.JD(a)&&!(400>=a.width||360>=a.height)};
g.k.JD=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.kf=function(){return this.rb&&g.JN(this.player)&&this.Oy()&&!this.B};
var P5a=[1,3,2,4];g.v(t6,g.X);g.k=t6.prototype;g.k.onClick=function(a){g.OO(this.getVideoUrl(),this.G,a);this.G.sb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.G.getVideoUrl(a,!1,!1,!0);var b=this.G.V();if(g.MF(b)||g.XF(b)){var c={};b.xa&&g.MF(b)&&g.kN(c,b.loaderUrl);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.jN(c,b);a=g.yi(a,c)}return a};
g.k.Wa=function(){this.G.Wa(this.element,this.rb&&this.xa)};
g.k.show=function(){g.X.prototype.show.call(this);this.Wa()};
g.k.hide=function(){g.X.prototype.hide.call(this);this.Wa()};
g.k.Ub=function(a){g.X.prototype.Ub.call(this,a);this.Wa()};g.v(u6,p6);u6.prototype.show=function(){3!==this.player.getPlayerState()&&(p6.prototype.show.call(this),this.j.Ax(!0),this.j.ip(!0),this.G.Wa(this.element,!0),this.watchButton.Ub(!0))};
u6.prototype.hide=function(){p6.prototype.hide.call(this);this.j.Ax(!1);this.j.ip(!1);this.G.Wa(this.element,!1);this.watchButton.Ub(!1)};g.v(J5a,p6);J5a.prototype.Ja=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.fl;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.v(v6,g.X);v6.prototype.select=function(){(this.api.Yl(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.kz||void 0)||this.api.N("web_player_endscreen_double_log_fix_killswitch"))&&this.api.sb(this.element)};
v6.prototype.onClick=function(a){g.NO(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
v6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.yx(a)||(this.select(),g.xx(a))}};
v6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.F?!1:b.B};g.v(w6,p6);g.k=w6.prototype;g.k.create=function(){p6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Vn();this.u.T(this.player,"appresize",this.Vn);this.u.T(this.player,"onVideoAreaChange",this.Vn);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.ZF);this.u.T(this.player,"autonavcancel",this.AV);a=this.videoData.autonavState;a!==this.S&&this.ZF(a);this.u.T(this.element,"transitionend",this.t4)};
g.k.destroy=function(){g.Xy(this.u);g.$e(this.stills);this.stills=[];p6.prototype.destroy.call(this);g.mo(this.element,"ytp-show-tiles");this.I.stop();this.S=this.videoData.autonavState};
g.k.Oy=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.rb;p6.prototype.show.call(this);K5a(this);g.mo(this.element,"ytp-show-tiles");this.player.V().isMobile?g.eo(this.I):this.I.start();(this.F||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.DN(this.player,!1);x6(this)?(y6(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Ix():3===this.videoData.autonavState&&this.j.Ot()):(g.DN(this.player,!0),y6(this));a!==this.rb&&
this.player.Wa(this.element,!0)};
g.k.hide=function(){var a=this.rb;p6.prototype.hide.call(this);this.j.Ot();y6(this);a!==this.rb&&this.player.Wa(this.element,!1)};
g.k.t4=function(a){g.tx(a)===this.element&&this.Vn()};
g.k.Vn=function(){var a=K5a(this);if(a.length){g.ko(this.element,"ytp-endscreen-paginate");var b=this.G.Kk(!0,this.G.isFullscreen()),c=g.yN(this.G);c&&(c=c.Ef()?48:32,b.width-=2*c);var d=b.width/b.height,e=96/54,f=c=2,h=Math.max(b.width/96,2),l=Math.max(b.height/54,2),m=a.length,n=Math.pow(2,2);var p=m*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-n;for(p-=n;0<p&&(c<h||f<l);){var q=c/2,r=f/2,w=c<=h-2&&p>=r*n,y=f<=l-2&&p>=q*n;if((q+1)/r*e/d>d/(q/(r+1)*e)&&y)p-=q*n,f+=2;else if(w)p-=r*n,c+=2;else if(y)p-=q*
n,f+=2;else break}e=!1;p>=3*n&&6>=m*n-p&&(4<=f||4<=c)&&(e=!0);n=96*c;p=54*f;d=n/p<d?b.height/p:b.width/n;d=Math.min(d,2);n=Math.floor(Math.min(b.width,n*d));p=Math.floor(Math.min(b.height,p*d));b=this.table.element;b.ariaLive="polite";g.Ol(b,n,p);g.El(b,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.LB(g.RH(this.videoData));this.j instanceof n6&&o6(this.j);g.O(this.element,"ytp-endscreen-takeover",x6(this));y6(this);n+=4;p+=4;d=0;b.ariaBusy="true";for(h=0;h<c;h++)for(l=0;l<f;l++)if(q=d,w=0,e&&
h>=c-2&&l>=f-2?w=1:0===l%2&&0===h%2&&(2>l&&2>h?0===l&&0===h&&(w=2):w=2),q=g.Ig(q+this.B,m),0!==w){r=this.stills[d];r||(r=new v6(this.player),this.stills[d]=r,b.appendChild(r.element));y=Math.floor(p*l/f);var z=Math.floor(n*h/c),B=Math.floor(p*(l+w)/f)-y-4,E=Math.floor(n*(h+w)/c)-z-4;g.Kl(r.element,z,y);g.Ol(r.element,E,B);g.El(r.element,"transitionDelay",(l+h)/20+"s");g.O(r.element,"ytp-videowall-still-mini",1===w);g.O(r.element,"ytp-videowall-still-large",2<w);this.Z&&(w=Math.max(E,B),g.O(r.element,
"ytp-videowall-still-round-large",256<=w),g.O(r.element,"ytp-videowall-still-round-medium",96<w&&256>w),g.O(r.element,"ytp-videowall-still-round-small",96>=w));q=a[q];r.suggestion!==q&&(r.suggestion=q,w=r.api.V(),y=g.jo(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",l6(r,q,y),g.MF(w)&&(y=q.Xm(),z={},w.xa&&g.kN(z,w.loaderUrl),y=g.yi(y,g.jN(z,"emb_rel_end")),r.Ma("url",y)),(q=(q=q.sessionData)&&q.itct)&&r.api.Ei(r.element,q));d++}b.ariaBusy="false";g.O(this.element,"ytp-endscreen-paginate",
d<m);for(a=this.stills.length-1;a>=d;a--)c=this.stills[a],g.ph(c.element),g.Ze(c);this.stills.length=d}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Vn())};
g.k.BV=function(){this.B+=this.stills.length;this.Vn()};
g.k.CV=function(){this.B-=this.stills.length;this.Vn()};
g.k.RQ=function(){return this.j.Ij()};
g.k.ZF=function(a){1===a?(this.F=!1,this.C=this.videoData.clientPlaybackNonce,this.j.qp(),this.rb&&this.Vn()):(this.F=!0,this.rb&&x6(this)&&(2===a?this.j.Ix():3===a&&this.j.Ot()))};
g.k.AV=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Wa(this.stills[a].element,!0);this.ZF(1)}else this.C=null,this.F=!1;this.Vn()};
g.k.kf=function(){return this.rb&&x6(this)};g.v(z6,p6);z6.prototype.show=function(){if(3!==this.player.getPlayerState()){p6.prototype.show.call(this);var a;null==(a=g.yN(this.player))||a.aB(!0);this.player.Wa(this.element,!0);this.watchButton.Ub(!0)}};
z6.prototype.hide=function(){p6.prototype.hide.call(this);var a;null==(a=g.yN(this.player))||a.aB(!1);this.player.Wa(this.element,!1);this.watchButton.Ub(!1)};g.v(O5a,g.mO);g.k=O5a.prototype;g.k.ou=function(){var a;if((null==(a=g.yN(this.player))?0:a.aj())||this.u)return!0;a=this.player.getVideoData();var b;var c=!!((null==a?0:g.RH(a))||(null==a?0:null==(b=a.suggestions)?0:b.length));b=!L5a(this.player)||c;c=a.oi||g.XF(a.u);var d=this.player.rz();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.kf=function(){return this.endScreen.kf()};
g.k.g0=function(){return this.kf()?this.endScreen.RQ():!1};
g.k.ra=function(){this.player.zf("endscreen");g.mO.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.xb().ue.get("heartbeat"),d=g.RH(a);!d||b.videoId!==d.videoId||a.yQ?(this.player.Yl(b.videoId,void 0,void 0,!0,!0,b),c&&c.PD("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.mO.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.mO.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.ou()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){N5a(this);this.C&&M5a(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new r6(this.player):this.endScreen=new w6(this.player),g.N(this,this.endScreen),g.IN(this.player,this.endScreen.element,4))};g.lO("endscreen",O5a);})(_yt_player);
