(function(g){var window=this;'use strict';var y6a=function(a){g.X.call(this,{D:"div",K:"ytp-inline-preview-ui"});this.wf=!1;this.player=a;this.T(a,"onStateChange",this.KL);this.T(a,"videodatachange",this.Qn);this.T(a,"onInlinePreviewModeChange",this.b0);this.Le=new g.$n(this.Jt,null,this);g.N(this,this.Le)},J6=function(a){g.mO.call(this,a);
this.j=new y6a(this.player);g.N(this,this.j);this.j.hide();g.IN(this.player,this.j.element,4);a.isInline()&&(this.load(),g.O(a.getRootNode(),"ytp-inline-preview-mode",!0),this.player.V().N("web_rounded_containers")&&g.O(a.getRootNode(),"ytp-rounded-inline-preview",!0),this.player.V().N("web_inline_player_disable_scrubbing")&&g.O(a.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",!0))};
g.v(y6a,g.X);g.k=y6a.prototype;
g.k.cJ=function(){this.tooltip=new g.mS(this.player,this);g.N(this,this.tooltip);g.IN(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Kc=new g.gP(this.player);g.N(this,this.Kc);var a=["ytp-inline-preview-scrim"];this.player.V().N("web_inline_player_expand_to_watch")||a.push("ytp-inline-preview-scrim-clear");this.Di=new g.X({D:"div",Ga:a});g.N(this,this.Di);this.Di.Ca(this.element);this.T(this.Di.element,"click",this.kE);this.player.V().N("web_inline_player_expand_to_watch")&&(a=new g.M2(this.player,
this),g.N(this,a),a.Ca(this.Di.element));this.Gi=new g.ZR(this.player,this);g.N(this,this.Gi);this.Gi.Ca(this.Di.element);this.controls=new g.X({D:"div",K:"ytp-inline-preview-controls"});g.N(this,this.controls);this.controls.Ca(this.element);a=new g.EQ(this.player,this);g.N(this,a);a.Ca(this.controls.element);a=new g.WR(this.player,this);g.N(this,a);a.Ca(this.controls.element);this.Cc=new g.TQ(this.player,this);g.N(this,this.Cc);g.IN(this.player,this.Cc.element,4);this.T(this.player,"appresize",this.Bb);
this.T(this.player,"fullscreentoggled",this.Bb);this.Bb()};
g.k.show=function(){g.ao(this.Le);this.wf||(this.cJ(),this.wf=!0);0!==this.player.getPlayerState()&&g.X.prototype.show.call(this);this.Cc.show()};
g.k.hide=function(){this.Le.stop();g.X.prototype.hide.call(this);this.player.isInline()||this.wf&&this.Cc.hide()};
g.k.ra=function(){g.X.prototype.ra.call(this)};
g.k.kE=function(a){a.target!==this.Di.element||this.player.V().N("web_inline_player_expand_to_watch")||this.player.Pa("onExpandInlinePreview",a)};
g.k.b0=function(){g.O(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.ge=function(){this.Cc.jc();this.Gi.jc()};
g.k.Jt=function(){this.ge();g.ao(this.Le)};
g.k.Bb=function(){g.lR(this.Cc,0,this.player.gb().getPlayerSize().width,!1);g.WQ(this.Cc)};
g.k.KL=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.Qn=function(a,b){this.player.isInline()&&g.O(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.QF)};
g.k.xc=function(){return this.tooltip};
g.k.Ef=function(){return!1};
g.k.Lg=function(){return!1};
g.k.aj=function(){return!1};
g.k.fh=function(){return!1};
g.k.Mk=function(){return!1};
g.k.ZA=function(){};
g.k.zo=function(){};
g.k.jw=function(){};
g.k.Um=function(){return null};
g.k.Fz=function(){return null};
g.k.Kk=function(){return new g.Bl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.St=function(a,b,c,d,e){var f=d=0,h=0,l=g.Pl(a);if(b){c=g.jo(b,"ytp-miniplayer-expand-watch-page-button");var m=g.jo(b,"ytp-mute-button"),n=g.jo(b,"ytp-subtitles-button"),p=g.Nl(b,this.element);b=g.Pl(b);d=p.y+40;c&&(h=8);if(n||m)h=p.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.gb().getPlayerSize().width;h=g.Hg(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.Nn=function(){};
g.k.Hk=function(){return!1};
g.k.aB=function(){};
g.k.Ax=function(){};
g.k.ip=function(){};
g.k.kC=function(){};
g.k.Zp=function(){};g.v(J6,g.mO);J6.prototype.Tj=function(){return!1};
J6.prototype.load=function(){this.player.hideControls();this.j.show()};
J6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.lO("inline_preview",J6);})(_yt_player);
